In [4]:
from analyze_classification_results import df_to_analyze
from pandas import DataFrame as DF
import pandas as pd

## LDA

In [6]:
LDA_results = results_df_gen()
LDA_results = gen_best_result_df('lda', 0, LDA_results)
LDA_results

,min_accu,max_accu,mean_accu,std_accu,mdn_accu,min_auc,max_auc,mean_auc,std_auc,mdn_auc,...,mdn_bal,min_f1,max_f1,mean_f1,std_f1,mdn_f1,df_len,model,hp,cols
0,66.667,85.714,73.234,5.875,72.222,68.304,90.179,81.454,6.214,81.515,...,72.179,64.516,87.500,72.580,6.846,70.588,187,lda,0,"['diff', 'color', 'elo', 'game_num']"
1,64.000,90.000,73.061,9.586,68.109,70.934,88.889,80.192,7.034,80.286,...,69.896,62.069,85.714,72.600,9.595,69.694,150,lda,0,"['diff', 'color', 'elo', 'opp_elo']"
2,66.667,92.857,76.129,8.501,72.727,70.089,91.071,82.751,5.918,83.538,...,75.777,66.667,93.333,75.456,8.680,73.864,187,lda,0,"['diff', 'color', 'elo']"
3,66.667,79.412,73.040,4.382,72.411,70.769,89.145,79.760,5.297,79.686,...,73.825,66.667,80.000,72.810,4.748,72.685,224,lda,0,"['diff', 'color', 'game_time', 'elo', 'game_num']"
4,62.857,90.000,73.463,9.434,69.631,71.280,88.889,80.126,6.926,80.710,...,71.949,58.064,85.714,72.861,9.902,71.198,150,lda,0,"['diff', 'color', 'game_time', 'elo', 'opp_elo']"
5,60.000,92.857,75.230,9.455,72.727,68.750,90.625,82.566,6.064,83.538,...,74.803,60.000,93.333,74.389,9.768,73.864,187,lda,0,"['diff', 'color', 'game_time', 'elo']"
6,65.790,80.000,73.145,4.733,73.620,68.182,96.023,80.899,7.670,80.212,...,73.812,64.865,84.210,73.826,6.253,73.545,264,lda,0,"['diff', 'color', 'game_time', 'game_num']"
7,63.158,83.333,73.090,6.179,71.915,71.091,91.477,81.022,6.131,79.585,...,72.130,63.158,87.805,73.984,7.127,72.772,264,lda,0,"['diff', 'color', 'game_time', 'opp_elo', 'gam..."
8,62.857,90.000,73.398,9.999,71.335,71.972,91.667,80.689,7.567,81.508,...,71.949,58.064,85.714,72.642,10.342,69.444,150,lda,0,"['diff', 'color', 'game_time', 'opp_elo']"
9,63.333,79.070,73.034,5.240,72.727,68.304,91.071,81.381,5.998,82.503,...,75.373,64.516,82.353,72.939,5.815,73.864,187,lda,0,"['diff', 'color', 'game_time', 'opp_elo']"
10,60.000,89.474,74.353,9.213,74.365,72.059,89.773,80.773,6.756,82.544,...,74.653,64.286,90.000,73.779,8.361,71.198,150,lda,0,"['diff', 'color', 'game_time', 'weekday', 'elo..."
11,63.333,79.070,73.134,5.387,73.128,69.196,88.170,80.601,5.052,81.615,...,74.315,64.516,80.000,72.947,5.715,72.984,187,lda,0,"['diff', 'color', 'game_time', 'weekday', 'elo..."
12,60.000,92.857,74.665,8.515,73.974,68.304,89.796,82.433,5.807,83.520,...,74.968,60.000,93.333,74.233,8.717,74.085,187,lda,0,"['diff', 'color', 'game_time', 'weekday', 'elo']"
13,62.963,89.474,74.794,8.844,75.717,73.356,89.773,81.414,6.621,83.153,...,76.123,62.069,90.000,74.104,8.393,72.364,150,lda,0,"['diff', 'color', 'game_time', 'weekday', 'opp..."
14,63.333,92.857,74.345,8.341,73.128,68.750,88.170,81.178,5.353,82.498,...,74.057,64.516,93.333,73.991,8.672,72.984,187,lda,0,"['diff', 'color', 'game_time', 'weekday', 'opp..."
15,68.000,83.333,73.635,5.315,72.732,70.546,91.477,80.971,5.993,79.883,...,72.916,68.085,87.805,74.410,6.321,72.019,264,lda,0,"['diff', 'color', 'opp_elo', 'game_num']"
16,62.857,90.000,73.030,9.893,68.606,70.934,91.667,80.888,7.629,81.774,...,71.949,58.064,85.714,72.120,10.462,71.484,150,lda,0,"['diff', 'color', 'opp_elo']"
17,63.333,92.857,73.113,8.256,72.727,69.643,90.848,81.636,5.949,80.767,...,72.800,60.000,93.333,72.185,8.843,72.009,187,lda,0,"['diff', 'color', 'time', 'elo']"
18,65.790,83.333,73.263,5.399,72.732,71.091,91.477,80.944,6.000,79.833,...,72.916,66.667,87.805,74.131,6.236,72.772,264,lda,0,"['diff', 'color', 'time', 'game_time', 'opp_el..."
19,63.333,81.081,73.272,4.905,72.727,68.304,91.071,80.585,6.165,81.082,...,73.964,64.516,82.353,73.415,5.319,72.727,187,lda,0,"['diff', 'color', 'time', 'game_time', 'opp_elo']"
20,63.333,85.714,74.443,6.007,73.974,69.196,88.393,79.797,5.186,79.851,...,74.559,64.516,87.500,74.559,6.470,72.949,187,lda,0,"['diff', 'color', 'time', 'game_time', 'weekda..."
21,60.000,92.857,73.040,8.218,72.475,68.750,89.796,81.338,5.630,81.813,...,72.390,60.000,93.333,72.404,8.642,71.405,187,lda,0,"['diff', 'color', 'time', 'game_time', 'weekda..."
22,58.824,90.000,73.736,11.514,71.146,69.204,88.636,79.651,7.191,80.528,...,73.153,50.000,90.000,72.700,12.185,70.483,150,lda,0,"['diff', 'color', 'time', 'game_time', 'weekda..."
23,63.333,92.857,75.211,8.065,73.974,68.750,88.393,80.817,5.267,80.877,...,74.559,64.516,93.333,75.066,8.298,72.949,187,lda,0,"['diff', 'color', 'time', 'game_time', 'weekda..."
24,66.667,92.857,73.479,7.248,72.475,69.196,89.796,81.329,5.606,81.082,...,72.390,66.667,93.333,72.996,7.588,71.405,187,lda,0,"['diff', 'color', 'time', 'weekday', 'elo']"
25,63.333,85.714,73.190,6.340,72.850,69.196,89.062,80.304,5.565,79.357,...,72.727,64.516,87.500,73.384,6.824,72.949,187,lda,0,"['diff', 'color', 'time', 'weekday', 'opp_elo']"
26,64.000,89.474,74.213,8.876,73.173,73.010,89.773,81.288,6.256,83.289,...,72.888,64.706,90.000,73.659,8.395,71.198,150,lda,0,"['diff', 'color', 'weekday', 'elo', 'opp_elo']"
27,66.667,92.857,75.564,7.436,74.603,68.750,89.796,82.356,5.702,83.421,...,76.119,66.667,93.333,75.064,7.496,73.864,187,lda,0,"['diff', 'color', 'weekday', 'elo']"
28,64.000,85.714,73.900,7.909,74.202,72.664,89.773,81.515,6.711,83.811,...,74.338,62.069,85.714,73.096,7.884,71.848,150,lda,0,"['diff', 'color', 'weekday', 'opp_elo']"
29,63.333,85.714,73.588,6.758,73.128,69.196,88.393,81.111,5.513,82.398,...,74.042,64.516,87.500,73.464,7.419,72.984,187,lda,0,"['diff', 'color', 'weekday', 'opp_elo']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,55.882,85.714,73.404,9.204,73.864,71.429,100.000,82.167,7.566,79.938,...,74.047,48.276,87.500,72.917,11.277,74.643,187,lda,0,"['diff', 'time', 'game_time', 'elo']"
63,63.830,79.365,73.025,4.343,73.527,73.818,94.886,81.571,6.497,80.575,...,73.768,63.830,82.192,74.135,5.174,74.815,264,lda,0,"['diff', 'time', 'game_time', 'game_num']"
64,63.333,85.714,73.481,7.413,72.475,71.429,91.837,79.695,6.584,79.793,...,72.758,64.516,87.500,74.307,7.676,74.342,187,lda,0,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
65,65.790,83.333,73.398,5.852,73.459,75.091,90.909,81.406,5.493,80.006,...,73.857,66.667,87.805,74.583,6.552,73.462,264,lda,0,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
66,66.667,92.857,74.727,8.540,72.222,71.875,100.000,81.554,7.849,81.012,...,72.272,66.667,93.333,75.229,8.679,72.259,187,lda,0,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
67,64.103,85.294,73.381,5.636,73.799,70.769,84.188,78.901,4.180,80.121,...,73.953,68.182,85.714,74.178,5.196,74.038,224,lda,0,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
68,65.790,80.000,73.461,4.684,72.324,75.857,95.454,82.603,6.227,80.661,...,72.980,66.667,85.000,74.202,5.339,73.093,264,lda,0,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
69,63.333,85.714,73.905,8.303,71.591,71.429,91.837,80.121,6.007,79.935,...,73.973,64.516,87.500,74.742,8.587,73.056,187,lda,0,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
70,68.000,83.333,73.419,5.013,72.219,75.286,92.046,81.759,5.576,80.081,...,72.828,68.085,87.805,74.182,5.977,72.861,264,lda,0,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
71,58.824,89.189,73.398,9.913,71.146,71.429,100.000,82.106,7.482,80.961,...,72.262,50.000,89.474,73.002,11.737,72.560,187,lda,0,"['diff', 'time', 'game_time', 'weekday', 'elo']"
72,65.957,82.540,73.873,4.708,74.621,74.000,96.591,81.729,6.890,80.496,...,74.460,66.667,84.932,74.650,5.677,74.292,264,lda,0,"['diff', 'time', 'game_time', 'weekday', 'game..."
73,60.000,92.857,73.741,10.175,72.475,70.982,93.878,80.340,6.551,80.476,...,72.361,60.000,93.333,74.235,10.349,73.799,187,lda,0,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
74,65.790,83.333,73.672,5.445,72.989,75.429,92.046,81.948,5.721,80.414,...,73.522,66.667,87.805,74.527,6.219,73.846,264,lda,0,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
75,65.790,83.333,73.552,5.930,73.459,74.909,90.909,81.342,5.331,80.367,...,73.857,66.667,87.805,74.700,6.586,73.462,264,lda,0,"['diff', 'time', 'opp_elo', 'game_num']"
76,65.909,92.857,74.552,9.276,72.222,72.982,100.000,81.886,7.609,81.851,...,72.179,66.667,93.333,75.091,9.230,72.136,187,lda,0,"['diff', 'time', 'weekday', 'elo', 'game_num']"
77,64.103,85.294,73.614,5.407,73.799,70.769,84.615,78.878,4.235,79.994,...,73.953,68.182,85.714,74.432,4.989,74.342,224,lda,0,"['diff', 'time', 'weekday', 'elo', 'game_num']"
78,65.790,80.000,73.461,4.684,72.324,76.286,94.886,82.696,5.831,80.537,...,72.980,66.667,85.000,74.202,5.339,73.093,264,lda,0,"['diff', 'time', 'weekday', 'elo', 'game_num']"
79,63.333,85.714,73.678,8.438,71.086,71.875,91.837,80.186,5.966,80.351,...,72.411,64.516,87.500,74.587,8.673,72.283,187,lda,0,"['diff', 'time', 'weekday', 'elo', 'opp_elo', ..."
80,68.000,83.333,73.641,5.165,72.219,74.857,92.046,81.770,5.560,80.462,...,72.828,68.085,87.805,74.359,6.011,72.861,264,lda,0,"['diff', 'time', 'weekday', 'elo', 'opp_elo', ..."
81,60.000,92.857,73.287,10.594,71.591,70.536,91.837,78.757,6.479,79.410,...,73.304,60.000,93.333,74.014,10.742,73.670,187,lda,0,"['diff', 'time', 'weekday', 'game_num']"
82,65.957,82.540,73.273,5.062,72.667,74.182,96.591,81.278,6.797,80.387,...,73.417,66.667,84.932,74.214,6.013,73.802,264,lda,0,"['diff', 'time', 'weekday', 'game_num']"
83,60.000,92.857,74.286,10.112,71.591,71.875,93.878,80.435,6.495,80.260,...,73.973,60.000,93.333,74.873,10.323,73.056,187,lda,0,"['diff', 'time', 'weekday', 'opp_elo', 'game_n..."
84,68.000,83.333,74.004,5.232,72.219,75.000,92.046,81.813,5.539,80.523,...,72.828,68.421,87.805,74.683,6.080,72.861,264,lda,0,"['diff', 'time', 'weekday', 'opp_elo', 'game_n..."
85,65.790,88.889,73.433,6.528,72.885,73.818,96.591,82.064,6.770,80.686,...,73.568,64.865,90.141,74.054,7.486,74.292,264,lda,0,"['diff', 'time', 'weekday']"
86,65.790,84.127,73.300,5.562,72.885,73.273,94.886,81.772,6.411,80.521,...,73.568,64.865,85.714,74.038,6.661,74.916,264,lda,0,"['diff', 'time']"
87,63.333,92.857,74.521,9.090,72.475,71.875,100.000,82.445,7.480,81.542,...,72.390,64.516,93.333,74.793,9.000,73.206,187,lda,0,"['diff', 'weekday', 'elo', 'game_num']"
88,67.924,83.333,73.199,5.642,71.172,75.857,92.046,81.918,5.474,80.526,...,71.347,66.667,87.805,73.948,6.681,72.637,264,lda,0,"['diff', 'weekday', 'elo', 'opp_elo', 'game_num']"
89,65.790,84.127,73.299,5.825,72.667,74.727,97.159,82.156,6.856,80.991,...,73.568,64.865,86.111,74.181,7.039,73.401,264,lda,0,"['diff', 'weekday', 'game_num']"
90,67.924,83.333,73.557,5.559,71.780,76.000,92.046,82.061,5.564,80.904,...,71.940,66.667,87.805,74.287,6.571,72.637,264,lda,0,"['diff', 'weekday', 'opp_elo', 'game_num']"
91,68.421,85.714,73.100,5.547,70.561,74.267,87.500,78.992,3.902,78.288,...,72.953,69.231,86.486,73.832,5.724,70.900,224,lda,0,"['game_time', 'elo', 'opp_elo', 'game_num']"

## Logistic

In [7]:
log_list = [-2, -1.75, -1.5, -1.25, -1.0, -0.75, -0.5, -0.25, 0.0, 0.25, 0.5,
            0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0]
log_results = results_df_gen()
for hp in log_list:
    log_results = gen_best_result_df('logistic', hp, log_results)
log_results

,min_accu,max_accu,mean_accu,std_accu,mdn_accu,min_auc,max_auc,mean_auc,std_auc,mdn_auc,...,mdn_bal,min_f1,max_f1,mean_f1,std_f1,mdn_f1,df_len,model,hp,cols
0,63.333,80.000,73.501,5.759,75.595,68.304,90.385,78.969,6.358,78.965,...,76.389,64.516,83.333,74.336,6.082,77.273,187,logistic,-2,"['diff', 'color', 'elo', 'opp_elo']"
1,66.667,90.000,74.432,7.885,72.283,72.321,100.000,82.056,7.365,80.797,...,72.421,66.667,90.909,75.041,8.371,73.419,187,logistic,-2,"['diff', 'elo', 'game_num']"
2,62.162,82.927,73.984,7.089,74.288,71.695,91.429,80.637,5.958,79.061,...,74.940,63.158,84.058,74.978,6.816,76.229,264,logistic,-2,"['diff', 'elo', 'game_num']"
3,60.000,90.000,73.056,9.330,69.158,70.536,92.000,80.026,6.034,79.333,...,69.778,60.000,90.909,73.712,9.660,69.859,187,logistic,-2,"['diff', 'elo', 'opp_elo', 'game_num']"
4,66.667,90.000,75.487,6.300,74.265,72.321,100.000,83.535,6.946,82.905,...,74.479,66.667,90.909,76.207,6.545,75.779,187,logistic,-2,"['diff', 'elo']"
5,56.667,90.000,73.192,9.208,70.178,69.643,92.000,80.363,6.560,80.936,...,70.861,55.172,90.909,73.796,9.878,71.039,187,logistic,-2,"['diff', 'game_num']"
6,66.667,90.000,74.959,7.099,73.547,72.321,100.000,81.994,7.362,80.127,...,74.333,66.667,90.909,75.557,7.759,75.000,187,logistic,-2,"['diff', 'game_time', 'elo', 'game_num']"
7,62.162,82.927,73.507,6.858,73.441,72.126,91.534,80.638,5.867,79.178,...,73.750,63.158,84.058,74.559,6.573,76.229,264,logistic,-2,"['diff', 'game_time', 'elo', 'game_num']"
8,60.000,90.000,73.306,8.423,70.821,70.089,92.000,81.074,5.805,80.841,...,72.143,60.000,90.909,74.007,8.631,71.848,187,logistic,-2,"['diff', 'game_time', 'elo', 'opp_elo']"
9,66.667,90.000,75.800,6.177,75.000,72.321,100.000,83.443,7.015,82.936,...,75.595,66.667,90.909,76.304,6.545,76.136,187,logistic,-2,"['diff', 'game_time', 'elo']"
10,60.000,90.000,73.053,8.359,71.807,70.982,92.000,81.587,5.617,81.520,...,72.357,60.000,90.909,74.134,8.243,71.919,187,logistic,-2,"['diff', 'game_time', 'opp_elo']"
11,66.667,90.000,75.015,6.823,72.951,72.321,96.000,81.311,6.320,81.540,...,74.333,66.667,90.909,76.020,7.188,74.661,187,logistic,-2,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
12,66.667,90.000,75.218,6.984,75.000,72.321,96.000,82.500,6.047,82.406,...,74.969,66.667,90.909,75.939,7.011,75.595,187,logistic,-2,"['diff', 'game_time', 'weekday', 'elo']"
13,60.000,90.000,73.147,8.354,71.429,70.536,96.000,80.435,6.830,80.683,...,71.861,60.000,90.909,74.172,8.799,73.913,187,logistic,-2,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
14,60.000,90.000,74.921,8.003,74.709,70.982,92.000,81.256,5.490,82.003,...,75.454,60.000,90.909,75.865,8.133,76.076,187,logistic,-2,"['diff', 'game_time', 'weekday', 'opp_elo']"
15,60.000,90.000,73.114,10.338,71.658,65.441,87.500,77.287,6.365,78.036,...,72.659,62.069,88.889,73.182,9.945,70.833,150,logistic,-2,"['diff', 'game_time', 'weekday']"
16,60.000,90.000,73.744,8.284,71.984,69.643,92.000,81.395,6.048,81.784,...,73.143,60.000,90.909,74.734,8.529,72.727,187,logistic,-2,"['diff', 'game_time']"
17,60.000,90.000,73.518,8.138,71.984,70.982,92.000,81.990,5.526,82.121,...,72.754,60.000,90.909,74.442,8.164,73.320,187,logistic,-2,"['diff', 'opp_elo']"
18,66.667,90.000,75.432,7.411,73.438,73.264,100.000,81.517,7.515,80.966,...,73.810,66.667,90.909,76.282,7.791,75.073,187,logistic,-2,"['diff', 'time', 'elo', 'game_num']"
19,64.865,82.258,74.822,5.495,76.064,71.264,91.111,80.349,6.256,78.886,...,76.944,66.667,84.058,75.814,4.963,76.596,264,logistic,-2,"['diff', 'time', 'elo', 'game_num']"
20,63.333,90.000,74.420,8.724,72.671,70.486,92.000,79.401,6.446,78.421,...,72.655,64.516,90.909,75.401,8.888,74.456,187,logistic,-2,"['diff', 'time', 'elo', 'opp_elo', 'game_num']"
21,66.667,90.000,75.456,6.728,74.456,72.768,100.000,82.296,7.260,81.268,...,74.738,66.667,90.909,76.266,6.938,75.593,187,logistic,-2,"['diff', 'time', 'elo']"
22,56.667,90.000,73.123,9.119,71.840,67.708,92.000,79.835,7.200,80.841,...,72.683,55.172,90.909,73.844,9.816,72.512,187,logistic,-2,"['diff', 'time', 'game_num']"
23,66.667,90.000,75.182,7.185,73.438,73.958,100.000,81.428,7.467,80.089,...,73.810,66.667,90.909,75.950,7.736,75.073,187,logistic,-2,"['diff', 'time', 'game_time', 'elo', 'game_num']"
24,62.162,82.258,74.040,6.183,74.902,71.983,91.429,80.351,6.083,78.976,...,75.724,63.158,84.058,75.037,5.734,76.596,264,logistic,-2,"['diff', 'time', 'game_time', 'elo', 'game_num']"
25,63.333,90.000,74.635,8.066,72.671,70.486,92.000,79.371,6.505,78.352,...,73.071,64.516,90.909,75.513,8.436,74.456,187,logistic,-2,"['diff', 'time', 'game_time', 'elo', 'opp_elo'..."
26,56.667,90.000,73.741,8.890,72.894,70.139,92.000,79.829,6.668,80.048,...,73.548,55.172,90.909,74.432,9.444,73.320,187,logistic,-2,"['diff', 'time', 'game_time', 'elo', 'opp_elo']"
27,66.667,90.000,76.331,6.856,75.595,72.768,100.000,82.051,7.340,80.349,...,76.587,66.667,90.909,77.151,7.248,77.346,187,logistic,-2,"['diff', 'time', 'game_time', 'elo']"
28,56.667,90.000,73.605,9.214,73.003,67.708,92.000,79.415,7.242,79.716,...,74.071,55.172,90.909,74.296,9.954,73.320,187,logistic,-2,"['diff', 'time', 'game_time', 'game_num']"
29,63.333,90.000,74.170,8.500,72.671,69.792,92.000,79.223,6.594,77.919,...,72.655,64.516,90.909,75.345,8.579,74.456,187,logistic,-2,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1551,63.333,82.609,75.008,6.575,75.960,70.536,90.466,79.973,6.444,78.929,...,76.522,62.069,85.185,75.644,7.710,77.318,187,logistic,3,"['diff', 'time', 'game_time']"
1552,60.000,84.210,74.322,7.773,74.842,70.536,95.556,81.208,7.149,80.465,...,74.925,60.000,85.714,75.265,7.884,75.304,187,logistic,3,"['diff', 'time', 'opp_elo', 'game_num']"
1553,66.667,81.667,73.339,4.393,73.670,73.715,93.333,82.726,6.364,81.584,...,74.417,69.565,83.077,74.603,4.408,74.497,264,logistic,3,"['diff', 'time', 'opp_elo', 'game_num']"
1554,56.667,84.210,74.007,7.995,74.486,70.982,91.111,81.836,5.835,81.696,...,74.598,55.172,85.714,74.711,8.482,75.304,187,logistic,3,"['diff', 'time', 'opp_elo']"
1555,63.333,89.474,74.764,7.418,75.305,72.321,96.667,81.357,7.304,80.801,...,75.238,62.069,88.889,75.114,7.367,76.923,187,logistic,3,"['diff', 'time', 'weekday', 'elo', 'game_num']"
1556,68.889,80.000,74.138,3.917,75.192,75.667,94.667,83.215,6.326,81.136,...,75.927,66.667,81.250,74.727,4.728,74.788,264,logistic,3,"['diff', 'time', 'weekday', 'elo', 'game_num']"
1557,66.667,89.474,75.584,7.024,73.370,71.875,95.556,82.112,6.443,81.883,...,75.076,66.667,90.000,76.424,6.902,75.196,187,logistic,3,"['diff', 'time', 'weekday', 'elo', 'opp_elo', ..."
1558,60.000,89.474,75.405,7.984,74.456,71.429,94.444,82.648,5.986,83.056,...,75.481,60.000,90.000,76.100,8.038,75.962,187,logistic,3,"['diff', 'time', 'weekday', 'elo', 'opp_elo']"
1559,63.333,84.210,75.025,5.983,74.342,71.429,94.444,81.705,6.233,82.187,...,75.076,64.516,84.210,75.466,6.303,75.962,187,logistic,3,"['diff', 'time', 'weekday', 'elo']"
1560,66.667,83.077,73.712,6.069,71.364,73.518,92.000,82.364,5.964,81.694,...,73.818,65.116,84.507,74.206,7.379,72.571,264,logistic,3,"['diff', 'time', 'weekday', 'game_num']"
1561,56.667,89.474,75.369,9.037,76.044,70.536,95.556,81.191,6.984,80.714,...,76.672,55.172,90.000,76.011,9.355,76.923,187,logistic,3,"['diff', 'time', 'weekday', 'opp_elo', 'game_n..."
1562,56.667,89.474,74.714,8.809,73.443,70.536,91.111,81.379,5.686,81.686,...,74.598,55.172,90.000,74.999,9.508,75.500,187,logistic,3,"['diff', 'time', 'weekday', 'opp_elo']"
1563,64.444,88.333,73.910,7.168,70.334,72.134,92.000,82.013,6.223,81.773,...,73.604,63.636,89.231,74.611,8.123,73.707,264,logistic,3,"['diff', 'time', 'weekday']"
1564,56.667,82.609,74.109,7.865,75.960,70.536,90.466,80.497,6.523,79.710,...,76.120,55.172,85.185,74.664,9.054,75.866,187,logistic,3,"['diff', 'time']"
1565,62.162,90.000,73.228,10.287,70.292,71.905,91.667,79.241,6.192,77.672,...,71.528,58.824,88.889,73.077,10.315,70.968,150,logistic,3,"['diff', 'weekday', 'elo', 'game_num']"
1566,66.667,89.474,75.081,7.032,73.370,71.875,96.667,82.577,6.774,82.505,...,74.468,66.667,88.889,75.882,6.771,75.716,187,logistic,3,"['diff', 'weekday', 'elo', 'game_num']"
1567,66.667,81.667,73.566,4.290,72.691,76.167,94.667,83.419,6.117,81.515,...,74.377,66.667,82.540,74.120,5.346,74.788,264,logistic,3,"['diff', 'weekday', 'elo', 'game_num']"
1568,66.667,89.474,76.117,6.690,74.342,71.429,95.556,82.612,6.364,83.056,...,75.076,66.667,90.000,76.802,6.662,75.304,187,logistic,3,"['diff', 'weekday', 'elo', 'opp_elo', 'game_num']"
1569,66.667,83.333,73.138,5.255,71.563,76.087,93.333,82.699,6.210,80.393,...,71.902,66.667,84.375,74.020,5.804,73.226,264,logistic,3,"['diff', 'weekday', 'elo', 'opp_elo', 'game_num']"
1570,66.667,89.474,76.872,6.517,75.500,71.875,94.444,83.189,5.912,84.048,...,77.027,66.667,90.000,77.153,6.511,77.171,187,logistic,3,"['diff', 'weekday', 'elo', 'opp_elo']"
1571,66.667,84.210,75.774,6.242,73.986,71.429,94.444,82.883,5.984,82.945,...,74.338,66.667,84.210,75.403,6.556,74.821,187,logistic,3,"['diff', 'weekday', 'elo']"
1572,60.000,84.210,73.434,7.957,72.842,69.196,92.222,79.979,6.262,80.516,...,72.842,60.000,85.714,73.996,8.486,73.879,187,logistic,3,"['diff', 'weekday', 'game_num']"
1573,68.085,83.333,73.213,5.335,69.906,73.913,92.000,82.534,5.815,81.964,...,74.191,65.116,85.294,73.922,6.370,73.707,264,logistic,3,"['diff', 'weekday', 'game_num']"
1574,63.333,89.474,75.285,8.144,74.956,70.089,94.444,81.742,6.582,81.439,...,75.810,62.069,90.000,75.758,8.318,76.923,187,logistic,3,"['diff', 'weekday', 'opp_elo', 'game_num']"
1575,60.000,89.474,73.901,7.791,71.714,70.982,91.111,82.357,5.504,82.488,...,71.995,60.000,90.000,73.744,8.230,72.667,187,logistic,3,"['diff', 'weekday', 'opp_elo']"
1576,58.621,90.000,73.195,9.921,68.848,69.762,87.500,78.666,5.667,78.452,...,71.543,60.000,88.889,73.184,9.911,72.078,150,logistic,3,"['diff', 'weekday']"
1577,60.000,82.609,73.631,6.851,72.486,69.643,90.365,82.030,6.009,82.122,...,72.896,60.000,85.185,73.972,7.593,72.111,187,logistic,3,['diff']
1578,66.667,89.474,76.189,6.563,74.956,72.321,95.556,82.380,6.936,82.133,...,77.027,66.667,88.889,76.563,6.544,75.962,187,logistic,3,"['game_time', 'elo', 'opp_elo', 'game_num']"
1579,64.865,84.210,74.303,6.797,77.024,71.875,95.556,83.141,6.853,83.834,...,76.969,64.865,84.210,74.640,7.004,77.935,187,logistic,3,"['game_time', 'weekday', 'elo', 'opp_elo']"
1580,62.162,84.210,73.817,7.220,73.714,69.412,93.333,80.342,7.712,79.480,...,74.439,63.158,84.210,74.406,7.250,74.176,187,logistic,3,"['time', 'game_time', 'weekday', 'elo', 'opp_e..."

## QDA

In [8]:
qda_list = [0.0, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
qda_results = results_df_gen()
for hp in qda_list:
    qda_results = gen_best_result_df('qda', hp, qda_results)
qda_results

,min_accu,max_accu,mean_accu,std_accu,mdn_accu,min_auc,max_auc,mean_auc,std_auc,mdn_auc,...,mdn_bal,min_f1,max_f1,mean_f1,std_f1,mdn_f1,df_len,model,hp,cols
0,62.857,79.032,73.411,4.923,73.684,75.733,89.766,80.820,4.735,79.367,...,74.160,62.857,80.000,73.717,5.085,74.643,264,qda,0.0,"['diff', 'elo', 'game_num']"
1,62.857,87.097,73.068,7.404,72.368,72.667,92.169,81.304,6.297,79.424,...,72.771,62.857,88.235,73.855,7.189,73.602,264,qda,0.0,"['diff', 'elo']"
2,65.714,80.000,73.835,4.253,73.583,72.667,85.965,79.822,4.501,80.703,...,74.136,66.667,81.579,75.248,4.942,75.000,264,qda,0.0,"['diff', 'game_time', 'game_num']"
3,67.273,78.947,73.128,3.671,73.577,71.600,87.134,79.964,4.415,79.479,...,73.988,66.667,80.000,73.532,4.113,73.933,264,qda,0.0,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
4,65.714,85.484,73.112,6.189,72.013,72.000,88.413,79.582,6.002,78.356,...,72.178,66.667,87.324,74.146,6.899,72.236,264,qda,0.0,"['diff', 'game_time']"
5,65.714,81.081,73.271,5.170,73.635,75.600,90.643,80.003,4.959,78.333,...,73.859,66.667,81.818,73.810,4.895,73.721,264,qda,0.0,"['diff', 'time', 'elo', 'game_num']"
6,65.714,83.784,73.864,5.999,73.635,73.067,90.688,80.835,5.509,80.050,...,73.966,66.667,84.058,74.651,5.786,73.937,264,qda,0.0,"['diff', 'time', 'elo']"
7,67.213,82.258,73.000,4.629,73.577,70.800,91.640,79.749,6.191,78.099,...,74.127,67.857,84.058,74.036,4.795,73.093,264,qda,0.0,"['diff', 'time', 'game_time', 'elo']"
8,68.571,77.193,73.179,2.559,73.727,72.667,83.333,79.136,3.628,80.408,...,73.855,68.571,79.365,74.256,3.393,73.765,264,qda,0.0,"['diff', 'time', 'game_time', 'game_num']"
9,67.273,80.328,73.108,4.405,72.201,71.200,88.571,79.318,5.424,78.809,...,72.397,66.667,84.210,74.086,5.889,73.397,264,qda,0.0,"['diff', 'time', 'game_time']"
10,65.714,83.871,74.646,5.602,74.534,72.267,87.196,79.875,5.036,79.293,...,75.060,64.706,85.294,75.229,6.700,75.974,264,qda,0.0,"['diff', 'time']"
11,62.857,81.081,73.034,6.050,72.507,73.067,88.148,80.076,5.642,79.335,...,72.949,62.857,82.353,74.029,6.472,73.103,264,qda,0.0,['diff']
12,62.162,78.462,73.014,5.236,73.364,76.923,89.234,80.976,4.375,80.202,...,73.601,63.158,79.412,73.720,4.937,75.205,264,qda,0.1,"['diff', 'elo', 'game_num']"
13,62.162,86.956,73.922,9.492,71.921,72.083,89.103,81.334,7.133,84.041,...,74.899,51.852,85.714,70.741,12.891,74.167,150,qda,0.1,"['diff', 'elo']"
14,64.865,78.462,74.125,3.878,74.705,77.490,88.756,80.976,3.883,79.848,...,75.141,64.865,78.788,74.859,4.235,75.410,264,qda,0.1,"['diff', 'game_time', 'elo', 'game_num']"
15,67.568,78.049,73.822,3.284,73.098,76.364,88.278,80.567,3.751,79.212,...,73.653,68.421,78.125,74.910,3.346,75.584,264,qda,0.1,"['diff', 'game_time', 'elo', 'opp_elo', 'game_..."
16,64.865,86.885,73.262,5.940,72.571,75.146,92.266,80.941,5.281,79.306,...,73.139,64.865,88.571,74.380,6.101,74.423,264,qda,0.1,"['diff', 'game_time', 'elo']"
17,62.162,81.538,73.311,4.974,74.507,73.091,86.364,80.392,4.367,81.573,...,74.303,61.111,82.353,74.591,6.004,76.095,264,qda,0.1,"['diff', 'game_time', 'game_num']"
18,67.568,78.688,73.620,3.257,73.098,75.091,88.756,80.396,4.207,79.005,...,73.653,68.421,79.365,74.810,3.156,75.584,264,qda,0.1,"['diff', 'game_time', 'opp_elo', 'game_num']"
19,70.000,78.049,74.042,2.257,73.620,76.471,86.603,80.294,3.430,80.205,...,74.587,66.667,78.431,74.646,3.742,75.379,264,qda,0.1,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
20,64.865,86.885,73.565,6.655,72.735,71.182,88.290,80.013,6.030,80.803,...,72.968,64.865,88.571,74.718,7.209,72.236,264,qda,0.1,"['diff', 'game_time']"
21,62.162,81.967,73.148,5.594,73.364,76.316,90.632,81.160,4.934,80.303,...,73.682,63.158,83.582,74.257,5.342,75.205,264,qda,0.1,"['diff', 'time', 'elo']"
22,64.865,78.688,73.018,4.608,73.607,74.000,85.633,79.871,3.895,79.857,...,74.324,64.865,80.000,73.626,5.144,75.543,264,qda,0.1,"['diff', 'time', 'game_num']"
23,68.085,83.607,73.102,4.067,72.571,77.091,91.830,80.641,5.230,78.403,...,73.139,69.388,85.714,74.508,4.652,74.423,264,qda,0.1,"['diff', 'time', 'game_time', 'elo']"
24,53.571,82.857,73.092,9.076,71.980,62.500,86.111,79.495,6.593,80.699,...,73.976,51.852,84.210,73.815,9.862,73.828,224,qda,0.1,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
25,60.714,86.956,74.217,6.678,73.576,61.979,84.091,78.006,6.075,79.382,...,73.613,56.000,86.956,74.493,8.147,74.130,224,qda,0.1,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
26,60.714,86.956,74.234,7.144,74.679,60.417,84.091,78.344,6.706,79.917,...,75.319,56.000,86.956,74.457,8.323,73.381,224,qda,0.1,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
27,57.143,82.609,73.584,7.079,74.389,61.979,83.333,78.748,6.301,80.671,...,76.212,50.000,83.333,73.654,9.195,73.799,224,qda,0.1,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
28,65.957,80.357,73.902,4.520,72.949,72.909,88.235,79.950,5.114,79.758,...,73.146,66.667,84.507,74.782,5.963,74.681,264,qda,0.1,"['diff', 'time', 'game_time']"
29,64.286,78.261,73.500,3.883,74.464,64.062,84.848,77.990,5.773,78.274,...,74.719,58.333,78.947,73.451,5.971,75.186,224,qda,0.1,"['diff', 'time', 'weekday', 'elo', 'game_num']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,62.745,88.000,73.096,8.123,71.364,70.186,97.619,81.398,8.142,79.622,...,71.598,64.151,90.909,73.519,8.914,71.252,264,qda,0.5,"['diff', 'weekday', 'opp_elo']"
154,64.706,80.000,73.215,4.956,74.097,71.273,92.857,80.917,6.278,79.974,...,74.744,64.865,84.848,73.473,5.634,73.691,264,qda,0.5,"['game_time', 'elo', 'opp_elo', 'game_num']"
155,60.870,85.714,73.366,8.904,73.452,69.388,93.878,80.824,6.571,80.641,...,74.547,60.870,87.500,73.498,9.703,72.698,187,qda,0.5,"['game_time', 'weekday', 'elo', 'opp_elo']"
156,64.286,85.714,73.340,7.236,72.233,70.175,97.959,79.294,8.338,78.929,...,76.786,64.865,87.500,74.423,7.546,71.919,187,qda,0.5,"['time', 'game_time', 'weekday', 'elo', 'opp_e..."
157,60.000,85.714,73.202,8.614,72.158,70.089,90.046,81.084,6.150,80.605,...,75.437,50.000,85.714,71.698,10.252,70.598,187,qda,1.0,"['diff', 'color', 'elo']"
158,60.714,90.000,73.644,11.099,69.385,70.918,93.182,81.040,7.329,80.827,...,71.455,59.259,85.714,72.362,11.096,67.041,150,qda,1.0,"['diff', 'color', 'game_time', 'weekday', 'elo..."
159,60.714,90.000,73.003,10.617,71.212,71.939,88.636,80.825,6.583,81.720,...,72.439,57.143,85.714,71.887,10.898,69.401,150,qda,1.0,"['diff', 'color', 'game_time', 'weekday', 'opp..."
160,63.158,86.000,73.250,6.516,73.221,71.324,86.667,79.704,6.124,80.893,...,73.445,61.111,87.273,73.566,7.796,73.986,299,qda,1.0,"['diff', 'color', 'time', 'game_time', 'elo', ..."
161,64.516,84.000,73.835,5.818,73.529,72.064,87.981,80.234,5.981,81.239,...,73.570,63.333,85.185,74.033,7.758,72.727,299,qda,1.0,"['diff', 'color', 'time', 'game_time', 'weekda..."
162,66.129,82.000,73.226,5.240,73.529,71.849,87.340,79.825,5.312,80.762,...,73.397,64.407,83.019,73.292,6.674,71.848,299,qda,1.0,"['diff', 'color', 'time', 'weekday', 'elo', 'g..."
163,60.714,90.000,73.644,11.099,69.385,70.918,93.182,81.040,7.329,80.827,...,71.455,59.259,85.714,72.362,11.096,67.041,150,qda,1.0,"['diff', 'color', 'weekday', 'elo', 'opp_elo']"
164,60.714,90.000,73.438,10.143,71.212,71.939,88.636,80.998,6.606,82.166,...,72.439,57.143,85.714,72.410,10.599,71.758,150,qda,1.0,"['diff', 'color', 'weekday', 'opp_elo']"
165,62.857,90.000,73.024,9.388,70.187,72.449,90.476,80.125,6.792,78.958,...,73.155,58.064,85.714,71.245,10.836,70.476,150,qda,1.0,"['diff', 'elo', 'opp_elo']"
166,62.857,90.000,73.024,9.388,70.187,72.449,90.476,80.042,6.844,78.542,...,73.155,58.064,85.714,71.245,10.836,70.476,150,qda,1.0,"['diff', 'game_time', 'elo', 'opp_elo']"
167,65.957,90.164,73.093,7.102,73.107,69.726,92.375,80.194,6.817,79.359,...,73.405,65.217,91.429,73.486,7.539,72.811,264,qda,1.0,"['diff', 'game_time', 'elo']"
168,65.909,80.328,73.372,5.672,75.066,70.048,88.453,79.802,6.791,80.109,...,75.209,65.116,83.333,74.037,6.658,75.671,264,qda,1.0,"['diff', 'game_time', 'game_num']"
169,62.000,83.607,73.067,6.642,73.955,70.048,91.612,79.808,6.879,79.434,...,75.162,62.745,85.294,73.635,6.805,74.914,264,qda,1.0,"['diff', 'game_time', 'opp_elo', 'game_num']"
170,60.714,90.000,73.148,9.971,69.631,71.429,90.476,80.544,6.531,79.345,...,73.036,57.143,85.714,71.255,10.983,70.077,150,qda,1.0,"['diff', 'game_time', 'weekday', 'elo', 'opp_e..."
171,65.790,81.967,73.037,5.673,72.844,70.370,89.434,79.853,6.776,80.317,...,72.709,64.865,84.932,73.576,7.005,71.625,264,qda,1.0,"['diff', 'game_time', 'weekday', 'game_num']"
172,65.790,85.246,73.297,7.228,71.536,69.008,90.033,79.280,7.267,79.267,...,71.964,64.865,87.324,73.906,8.404,71.884,264,qda,1.0,"['diff', 'game_time', 'weekday']"
173,68.000,83.607,73.710,5.112,74.133,69.887,91.285,80.069,6.774,79.102,...,74.451,68.085,85.294,74.347,5.485,74.306,264,qda,1.0,"['diff', 'time', 'game_time', 'elo', 'game_num']"
174,65.790,88.525,73.094,6.594,71.149,69.726,93.137,80.072,6.702,79.006,...,71.443,66.667,89.855,73.521,7.157,70.949,264,qda,1.0,"['diff', 'time', 'game_time', 'weekday', 'elo']"
175,63.636,83.607,73.497,5.533,73.252,70.692,88.998,79.732,6.642,80.364,...,73.173,61.905,86.111,74.027,7.047,72.261,264,qda,1.0,"['diff', 'time', 'game_time', 'weekday', 'game..."
176,63.636,85.000,73.567,6.406,73.508,70.041,90.250,79.197,6.966,79.552,...,73.921,61.905,87.671,73.825,8.052,73.287,264,qda,1.0,"['diff', 'time', 'game_time', 'weekday']"
177,64.516,80.000,73.057,5.356,72.794,70.000,88.447,79.657,6.728,80.676,...,72.835,62.069,83.333,73.091,7.193,72.596,299,qda,1.0,"['diff', 'time', 'game_time', 'weekday']"
178,59.091,85.246,73.547,6.972,75.039,70.661,88.562,79.345,6.695,79.626,...,75.237,57.143,87.324,73.978,8.358,74.456,264,qda,1.0,"['diff', 'time', 'game_time']"
179,63.636,86.885,73.282,7.427,73.508,70.531,89.161,79.124,6.306,79.218,...,73.811,61.905,88.571,73.679,8.454,72.821,264,qda,1.0,"['diff', 'time', 'weekday']"
180,60.714,90.000,73.148,9.971,69.631,71.429,90.476,80.544,6.531,79.345,...,73.036,57.143,85.714,71.255,10.983,70.077,150,qda,1.0,"['diff', 'weekday', 'elo', 'opp_elo']"
181,62.500,85.714,73.100,8.751,72.841,66.942,89.583,80.017,6.950,79.698,...,74.434,57.143,85.714,72.698,9.650,73.718,187,qda,2.0,"['diff', 'elo']"
182,64.444,81.667,73.279,5.607,72.999,72.727,90.526,80.309,5.914,78.930,...,74.173,61.905,84.932,73.372,6.860,73.704,264,qda,2.0,"['diff', 'weekday']"

## Ridge Classifier

In [9]:
ridge_list = [-1, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
ridge_results = results_df_gen()
for hp in ridge_list:
    ridge_results = gen_best_result_df('ridge', hp, ridge_results)
ridge_results

,min_accu,max_accu,mean_accu,std_accu,mdn_accu,min_auc,max_auc,mean_auc,std_auc,mdn_auc,...,mdn_bal,min_f1,max_f1,mean_f1,std_f1,mdn_f1,df_len,model,hp,cols
0,58.064,84.210,74.348,8.372,73.986,57.917,84.659,75.219,7.870,74.492,...,74.492,60.606,85.714,74.961,8.341,72.984,150,ridge,-1,"['diff', 'elo', 'game_num']"
1,56.250,90.000,73.114,10.287,70.197,57.936,91.667,74.060,10.330,73.510,...,73.510,58.824,90.909,73.209,10.988,72.150,150,ridge,-1,"['diff', 'elo', 'opp_elo']"
2,62.500,90.000,74.498,10.729,70.197,64.375,91.667,75.433,10.519,73.510,...,73.510,60.000,90.909,74.759,11.216,72.150,150,ridge,-1,"['diff', 'elo']"
3,60.000,83.333,73.594,6.812,76.619,60.000,85.000,74.756,7.220,76.726,...,76.726,50.000,84.210,73.200,9.716,77.486,187,ridge,-1,"['diff', 'elo']"
4,58.064,81.818,73.858,8.038,77.124,57.917,81.667,74.543,8.069,77.451,...,77.451,60.606,83.333,74.832,8.369,76.389,150,ridge,-1,"['diff', 'game_num']"
5,58.064,84.210,73.658,9.116,73.986,57.917,84.659,74.486,8.567,74.492,...,74.492,60.606,85.714,74.316,8.914,72.794,150,ridge,-1,"['diff', 'game_time', 'elo', 'game_num']"
6,58.621,90.000,73.231,10.865,69.538,61.364,91.667,74.219,10.599,71.349,...,71.349,60.000,90.909,73.355,11.326,70.000,150,ridge,-1,"['diff', 'game_time', 'elo']"
7,60.000,83.333,73.888,6.731,76.619,60.000,85.000,75.019,7.139,76.726,...,76.726,50.000,84.210,73.570,9.676,77.486,187,ridge,-1,"['diff', 'game_time', 'elo']"
8,58.064,90.000,73.223,9.567,72.850,57.917,91.667,74.463,9.623,72.786,...,72.786,60.606,90.909,73.673,9.115,72.794,150,ridge,-1,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
9,60.000,88.889,74.385,8.705,73.756,60.000,90.000,75.460,8.490,74.533,...,74.533,50.000,88.889,73.830,10.871,74.614,187,ridge,-1,"['diff', 'game_time', 'weekday', 'elo']"
10,58.064,88.000,73.645,9.377,70.197,57.917,88.312,74.494,9.177,73.510,...,73.510,60.606,88.889,74.263,9.672,72.150,150,ridge,-1,"['diff', 'time', 'elo', 'game_num']"
11,60.000,83.333,73.914,6.666,75.304,60.000,85.000,75.015,7.052,75.337,...,75.337,50.000,84.210,73.760,9.579,75.973,187,ridge,-1,"['diff', 'time', 'elo']"
12,60.000,88.889,73.450,7.566,72.094,60.000,90.000,74.421,7.715,73.362,...,73.362,50.000,88.889,73.379,9.944,73.207,187,ridge,-1,"['diff', 'time', 'weekday', 'elo']"
13,58.064,90.000,73.912,8.899,72.850,57.917,91.667,75.195,9.010,72.786,...,72.786,60.606,90.909,74.318,8.609,72.984,150,ridge,-1,"['diff', 'weekday', 'elo', 'game_num']"
14,60.000,88.889,74.052,8.952,73.756,60.000,90.000,75.103,8.790,74.533,...,74.533,50.000,88.889,73.400,11.080,74.547,187,ridge,-1,"['diff', 'weekday', 'elo']"
15,60.000,88.889,73.621,9.234,73.205,60.000,90.000,74.481,9.417,74.457,...,74.457,50.000,88.889,73.315,11.412,75.931,187,ridge,-1,"['diff', 'weekday', 'opp_elo']"
16,56.250,90.000,73.156,10.532,75.493,57.936,91.667,73.974,10.830,77.178,...,77.178,58.824,90.909,73.358,11.468,76.389,150,ridge,-1,['diff']
17,58.064,84.000,74.022,8.001,73.986,57.917,83.766,74.947,7.548,74.492,...,74.492,60.606,85.714,74.726,8.140,72.984,150,ridge,-0.5,"['diff', 'elo', 'game_num']"
18,61.224,81.967,73.176,6.261,73.026,61.448,81.917,73.457,6.281,73.477,...,73.477,62.745,83.582,74.011,6.450,74.497,264,ridge,-0.5,"['diff', 'elo', 'game_num']"
19,67.742,85.714,74.308,5.418,73.799,67.752,85.714,75.079,5.224,74.056,...,74.056,65.517,86.207,74.990,5.800,74.597,299,ridge,-0.5,"['diff', 'elo', 'game_num']"
20,62.500,90.000,74.122,10.199,70.197,64.375,91.667,75.124,10.106,73.510,...,73.510,60.000,90.909,74.430,10.843,72.150,150,ridge,-0.5,"['diff', 'elo']"
21,66.667,80.488,73.519,4.938,75.500,66.964,80.595,74.277,4.853,75.481,...,75.481,66.667,80.000,74.023,5.138,76.923,187,ridge,-0.5,"['diff', 'elo']"
22,58.064,81.818,73.582,7.890,75.933,57.917,81.667,74.309,7.922,76.757,...,76.757,60.606,83.333,74.673,8.322,75.595,150,ridge,-0.5,"['diff', 'game_num']"
23,58.064,84.000,73.332,8.748,73.986,57.917,83.766,74.215,8.246,74.492,...,74.492,60.606,85.714,74.081,8.707,72.794,150,ridge,-0.5,"['diff', 'game_time', 'elo', 'game_num']"
24,63.265,81.967,73.226,5.672,73.026,63.300,81.917,73.498,5.682,73.477,...,73.477,65.385,83.582,74.294,5.703,74.497,264,ridge,-0.5,"['diff', 'game_time', 'elo', 'game_num']"
25,67.742,85.714,73.541,6.062,71.614,67.752,85.714,74.320,6.030,73.284,...,73.284,65.517,86.207,74.143,6.625,73.716,299,ridge,-0.5,"['diff', 'game_time', 'elo', 'game_num']"
26,58.621,90.000,73.381,11.043,69.538,61.364,91.667,74.364,10.766,71.349,...,71.349,60.000,90.909,73.540,11.504,70.000,150,ridge,-0.5,"['diff', 'game_time', 'elo']"
27,65.217,80.488,73.794,5.043,75.838,65.217,80.595,74.587,5.053,76.069,...,76.069,65.217,80.000,74.233,5.364,76.923,187,ridge,-0.5,"['diff', 'game_time', 'elo']"
28,64.516,87.500,73.074,6.665,71.585,64.496,87.500,73.874,6.589,72.590,...,72.590,62.069,88.136,73.570,7.169,72.685,299,ridge,-0.5,"['diff', 'game_time', 'elo']"
29,67.924,81.081,73.273,4.222,72.512,67.949,80.848,73.686,4.218,73.431,...,73.431,66.667,82.927,73.987,5.199,75.000,224,ridge,-0.5,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,65.790,82.609,73.824,6.099,73.714,65.833,84.990,74.321,6.499,73.782,...,73.782,64.865,84.615,74.552,6.599,75.000,187,ridge,4,"['diff', 'time', 'elo', 'opp_elo', 'game_num']"
404,62.712,88.679,73.083,6.803,73.499,62.732,88.746,73.539,6.727,73.821,...,73.821,60.714,88.889,73.635,7.135,73.985,299,ridge,4,"['diff', 'time', 'elo', 'opp_elo', 'game_num']"
405,56.667,80.769,73.046,7.450,74.486,56.696,83.266,73.604,7.843,74.929,...,74.929,55.172,82.759,73.906,7.999,74.342,187,ridge,4,"['diff', 'time', 'elo', 'opp_elo']"
406,68.421,81.818,75.600,4.453,75.500,68.889,81.818,76.320,4.667,76.667,...,76.667,70.000,81.482,76.319,4.225,76.210,187,ridge,4,"['diff', 'time', 'elo']"
407,66.667,79.546,73.122,4.857,74.709,66.964,81.542,73.754,5.384,74.675,...,74.675,66.667,80.000,73.737,5.288,75.278,187,ridge,4,"['diff', 'time', 'game_time', 'elo', 'game_num']"
408,65.714,82.759,73.400,5.314,71.455,65.686,82.933,74.026,5.601,72.555,...,72.555,66.667,81.482,73.789,4.274,75.000,264,ridge,4,"['diff', 'time', 'game_time', 'elo', 'game_num']"
409,64.407,88.679,73.280,6.523,72.429,64.294,88.746,73.795,6.550,73.650,...,73.650,61.818,88.889,73.800,7.047,73.953,299,ridge,4,"['diff', 'time', 'game_time', 'elo', 'game_num']"
410,65.790,82.609,73.554,6.329,73.714,65.833,84.990,74.027,6.742,73.782,...,73.782,64.865,84.615,74.367,6.756,75.000,187,ridge,4,"['diff', 'time', 'game_time', 'elo', 'opp_elo'..."
411,67.213,82.759,73.188,5.154,72.000,68.464,82.933,73.875,5.321,72.632,...,72.632,69.388,81.482,73.659,3.743,73.255,264,ridge,4,"['diff', 'time', 'game_time', 'elo', 'opp_elo'..."
412,68.421,81.818,75.600,4.453,75.500,68.889,81.818,76.320,4.667,76.667,...,76.667,70.000,81.482,76.319,4.225,76.210,187,ridge,4,"['diff', 'time', 'game_time', 'elo']"
413,66.667,82.609,73.433,5.635,73.714,66.964,84.990,73.920,6.162,73.782,...,73.782,66.667,84.615,74.128,6.023,75.000,187,ridge,4,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
414,67.213,82.759,73.043,4.908,72.000,68.464,82.933,73.804,5.021,72.632,...,72.632,69.388,81.482,73.508,3.823,72.000,264,ridge,4,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
415,64.407,86.792,73.296,5.774,73.221,64.583,86.966,73.991,5.977,73.278,...,73.278,63.158,87.719,73.777,6.674,73.106,299,ridge,4,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
416,68.571,80.000,73.150,4.272,71.849,68.628,82.500,73.782,4.500,72.495,...,72.495,68.085,81.159,72.866,3.924,72.232,264,ridge,4,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
417,66.102,86.792,73.315,5.622,73.499,66.435,86.966,74.002,5.794,73.972,...,73.972,65.517,87.719,73.822,6.340,73.751,299,ridge,4,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
418,70.000,79.546,73.349,2.656,73.025,70.536,79.546,74.076,2.472,74.066,...,74.066,70.968,79.070,74.408,2.623,73.879,187,ridge,4,"['diff', 'time', 'game_time', 'weekday', 'elo']"
419,68.000,81.538,73.356,4.746,71.921,69.500,82.738,74.157,5.272,71.844,...,71.844,66.667,83.333,73.170,5.719,71.131,264,ridge,4,"['diff', 'time', 'game_time', 'weekday', 'game..."
420,64.407,86.792,73.289,5.815,73.499,64.583,86.966,73.983,6.018,73.972,...,73.972,63.158,87.719,73.776,6.703,73.751,299,ridge,4,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
421,66.667,82.609,73.703,5.381,73.714,66.964,84.990,74.214,5.902,73.782,...,73.782,66.667,84.615,74.313,5.855,75.000,187,ridge,4,"['diff', 'time', 'opp_elo', 'game_num']"
422,64.407,88.679,73.143,6.702,73.163,64.583,88.746,73.646,6.579,73.321,...,73.321,63.158,88.889,73.915,6.764,73.509,299,ridge,4,"['diff', 'time', 'opp_elo', 'game_num']"
423,56.667,79.546,73.034,6.878,74.486,56.696,81.542,73.625,7.309,75.011,...,75.011,55.172,80.000,73.829,7.422,75.000,187,ridge,4,"['diff', 'time', 'opp_elo']"
424,64.407,86.792,73.033,6.073,73.221,64.583,86.966,73.728,6.299,73.278,...,73.278,63.158,87.719,73.596,6.907,73.106,299,ridge,4,"['diff', 'time', 'weekday', 'elo', 'game_num']"
425,66.102,86.792,73.195,5.616,73.221,66.435,86.966,73.810,5.872,73.278,...,73.278,65.517,87.719,73.686,6.507,73.025,299,ridge,4,"['diff', 'time', 'weekday', 'elo', 'opp_elo', ..."
426,68.000,81.538,73.071,4.769,71.429,69.500,82.738,73.863,5.352,71.407,...,71.407,66.667,83.333,72.971,5.657,71.131,264,ridge,4,"['diff', 'time', 'weekday', 'game_num']"
427,64.407,86.792,73.153,5.804,73.221,64.583,86.966,73.844,6.023,73.278,...,73.278,63.158,87.719,73.676,6.708,73.251,299,ridge,4,"['diff', 'time', 'weekday', 'opp_elo', 'game_n..."
428,67.273,80.000,73.177,4.540,72.000,67.667,82.500,73.821,4.711,72.632,...,72.632,67.857,81.159,72.929,3.943,72.770,264,ridge,4,"['diff', 'weekday', 'elo', 'opp_elo', 'game_num']"
429,61.290,90.000,73.344,10.025,68.858,61.042,92.857,74.419,10.396,71.544,...,71.544,61.538,86.956,72.280,10.199,68.858,150,ridge,4,"['diff', 'weekday', 'elo']"
430,66.667,81.395,73.646,4.951,73.500,66.964,81.385,74.511,4.627,75.000,...,75.000,66.667,81.818,73.604,5.376,74.095,187,ridge,4,"['diff', 'weekday', 'elo']"
431,66.102,86.792,73.068,5.886,72.458,66.146,86.823,73.706,6.054,72.467,...,72.467,64.286,86.792,73.289,6.471,72.464,299,ridge,4,"['diff', 'weekday', 'elo']"
432,61.290,90.000,73.532,10.177,71.232,61.042,92.857,74.866,10.618,74.144,...,74.144,64.706,86.956,73.963,9.124,70.968,150,ridge,4,"['game_time', 'elo', 'opp_elo', 'game_num']"

## Gaussian Process Classifier

In [21]:
gauz_list = [1, 3, 5, 6, 8, 10, 12, 13, 14, 15, 17, 18, 19, 21, 22, 24,
             25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 37, 38, 39]
gauz_results = results_df_gen()
for hp in range(1, 40):
    try:
        gauz_results = gen_best_result_df('gaussian', hp, gauz_results)
    except FileNotFoundError:
        i += 1
        print(i)
print(f'Gaussian done: {len(gauz_results)}')
gauz_results

LDA done: 92

[autoreload of analyze_classification_results failed: Traceback (most recent call last):
  File "/home/guess/anaconda3/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 1422, in f
    alias, alt=npfunc, **kwargs)
  File "/home/guess/anaconda3/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 3972, in _cython_agg_general
    how, alt=alt, numeric_only=numeric_only, min_count=min_count)
  File "/home/guess/anaconda3/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 4038, in _cython_agg_blocks
    newb = block.make_block(result)
  File "/home/guess/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 261, in make_block
    return make_block(values, placement=placement, ndim=ndim)
  File "/home/guess/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 3198, in make_block
    dtype = dtype or values.dtype
  File "/home/guess/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'dtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guess/anaconda3/lib/python3.6/site-packages/pandas/core/nanops.py", line 121, in f
    result = bn_func(values, axis=axis, **kwds)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guess/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/guess/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 376, in superreload
    module = reload(module)
  File "/home/guess/anaconda3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/guess/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/guess/Dropbox/lots-of-data/src/analyze_classification_results.py", line 166, in <module>
    get_combined_results_df(ND='-nb')
  File "/home/guess/Dropbox/lots-of-data/src/analyze_classification_results.py", line 100, in get_combined_results_df
    log_results = gen_best_result_df('logistic', lc, log_results)
  File "/home/guess/Dropbox/lots-of-data/src/analyze_classification_results.py", line 44, in gen_best_result_df
    (classifier + str(hp)))
KeyboardInterrupt
]

NameError: name 'i' is not defined

In [20]:
gauz_list = [1, 3, 5, 6, 8, 10, 12, 13, 14, 15, 17, 18, 19, 21, 22, 24,
             25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 37, 38, 39]
gauz_results = results_df_gen()
for hp in gauz_list:
    gauz_results = gen_best_result_df('gaussian', hp, gauz_results)
gauz_results

FileNotFoundError: File b'../data/gaussian0_results-nb.csv' does not exist

## K-Nearest Neighbor Classifier

In [12]:
knn_results = results_df_gen()
for hp in (range(2, 40)):
    knn_results = gen_best_result_df('knn', hp, knn_results)
knn_results

,min_accu,max_accu,mean_accu,std_accu,mdn_accu,min_auc,max_auc,mean_auc,std_auc,mdn_auc,...,mdn_bal,min_f1,max_f1,mean_f1,std_f1,mdn_f1,df_len,model,hp,cols
0,62.963,83.871,73.036,6.098,73.058,59.722,81.624,75.137,6.599,76.592,...,72.749,64.286,86.486,75.684,6.194,76.393,224,knn,6,"['diff', 'game_time', 'weekday', 'game_num']"
1,60.526,88.000,73.055,8.793,72.884,69.082,90.079,78.130,7.873,77.108,...,73.432,63.415,91.892,74.851,9.269,73.599,264,knn,6,"['diff', 'opp_elo', 'game_num']"
2,65.957,87.500,73.342,5.704,72.429,69.887,91.479,77.533,6.267,77.066,...,71.526,66.667,88.372,75.487,6.439,74.995,264,knn,6,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
3,66.667,80.392,73.483,4.145,74.306,61.944,82.935,74.216,6.318,74.939,...,74.153,66.667,81.482,75.750,4.443,76.331,224,knn,6,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
4,61.765,84.000,73.220,7.270,73.799,65.977,86.111,76.781,8.272,78.720,...,74.515,58.064,87.500,73.435,10.661,76.299,150,knn,6,"['diff', 'time', 'opp_elo']"
5,67.742,80.392,73.160,3.714,72.850,59.188,81.354,73.183,7.432,75.581,...,72.607,69.231,81.482,75.849,3.748,75.483,224,knn,6,"['diff', 'time', 'weekday', 'opp_elo', 'game_n..."
6,64.151,86.046,73.052,6.244,73.583,69.000,86.111,78.560,4.798,78.178,...,73.638,62.500,88.000,72.426,7.583,71.825,224,knn,7,"['diff', 'game_time', 'game_num']"
7,63.415,84.210,73.328,6.420,74.935,68.933,82.784,75.816,3.867,75.717,...,75.641,61.538,80.000,71.604,7.096,73.397,224,knn,7,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
8,66.038,82.979,73.491,5.496,74.512,70.467,86.905,76.384,4.879,74.875,...,75.223,62.500,80.952,72.832,6.489,73.944,224,knn,7,"['diff', 'game_time', 'weekday', 'elo', 'opp_e..."
9,66.667,78.947,73.142,4.260,73.221,72.400,81.868,77.450,3.404,77.357,...,73.224,66.667,79.167,73.476,3.945,74.211,224,knn,7,"['diff', 'game_time', 'weekday', 'game_num']"
10,65.854,81.081,73.374,4.332,73.401,71.600,87.637,78.232,5.359,76.974,...,73.679,68.182,81.081,73.474,4.182,72.756,224,knn,7,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
11,64.444,78.947,73.195,4.448,73.831,71.067,81.605,76.302,3.325,76.197,...,73.224,65.217,79.167,73.684,4.695,74.543,224,knn,7,"['diff', 'weekday', 'game_num']"
12,65.454,78.261,73.675,4.436,74.456,73.160,86.240,78.783,4.373,77.770,...,74.808,64.151,81.482,75.545,5.607,76.446,224,knn,8,"['diff', 'color', 'game_time', 'opp_elo', 'gam..."
13,58.064,88.000,73.200,9.551,72.635,64.167,90.909,77.438,7.371,77.083,...,74.994,58.064,88.889,73.341,9.673,75.073,150,knn,8,"['diff', 'elo']"
14,60.000,85.366,75.522,8.185,75.464,70.667,86.134,79.526,5.475,78.855,...,75.300,62.069,86.792,77.459,7.671,77.500,224,knn,8,"['diff', 'game_num']"
15,60.000,86.207,73.410,8.022,71.868,67.246,92.208,78.309,8.328,75.190,...,73.940,61.111,90.000,74.023,8.576,72.702,264,knn,8,"['diff', 'game_time', 'elo', 'opp_elo', 'game_..."
16,65.454,84.444,75.063,5.401,74.540,66.733,86.029,79.268,5.442,79.513,...,74.419,65.454,86.792,76.833,5.655,76.818,224,knn,8,"['diff', 'game_time', 'game_num']"
17,63.636,83.784,74.011,5.306,74.489,68.133,85.385,78.677,5.659,79.752,...,75.004,61.538,85.000,74.893,6.186,75.736,224,knn,8,"['diff', 'game_time', 'opp_elo', 'game_num']"
18,63.636,82.979,74.235,5.608,74.422,68.733,87.729,77.413,4.736,77.056,...,74.232,62.963,82.609,75.421,5.956,76.889,224,knn,8,"['diff', 'game_time', 'weekday', 'elo', 'opp_e..."
19,60.870,82.609,74.269,6.758,77.011,72.396,86.538,79.184,5.324,79.366,...,76.786,60.870,85.185,75.943,7.389,78.084,224,knn,8,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
20,68.571,86.207,74.067,6.027,71.754,72.669,88.471,78.507,5.642,77.113,...,71.913,69.091,90.476,74.934,6.967,72.727,264,knn,8,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
21,61.290,85.714,73.485,8.269,71.842,62.292,84.091,76.287,6.818,77.512,...,75.284,53.846,88.235,73.298,10.774,74.680,150,knn,8,"['diff', 'game_time', 'weekday']"
22,60.870,79.592,73.534,6.235,75.254,66.154,83.480,76.346,5.209,77.116,...,75.438,64.000,81.482,75.835,5.925,77.350,224,knn,8,"['diff', 'game_time']"
23,60.976,83.784,73.352,7.095,74.191,70.573,84.231,76.753,4.482,76.600,...,74.684,67.857,84.210,74.838,5.752,73.320,224,knn,8,"['diff', 'opp_elo']"
24,65.454,78.261,73.237,4.467,74.755,73.267,86.905,79.061,4.377,77.425,...,74.654,66.667,80.000,75.167,4.255,76.239,224,knn,8,"['diff', 'time', 'game_time', 'game_num']"
25,63.415,81.081,73.672,5.175,74.755,69.531,85.385,78.046,5.712,77.850,...,74.817,65.116,82.927,75.025,5.351,75.960,224,knn,8,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
26,67.568,84.000,73.040,5.403,71.198,62.500,89.610,78.104,7.972,78.799,...,72.768,57.143,84.615,73.263,8.715,76.073,150,knn,8,"['diff', 'time', 'game_time', 'opp_elo']"
27,65.217,79.592,73.237,5.362,73.922,69.792,82.981,76.507,4.163,75.013,...,74.167,66.667,80.769,75.014,5.325,76.480,224,knn,8,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
28,68.421,82.759,73.574,4.638,71.548,71.712,84.250,77.931,5.119,77.534,...,73.947,67.857,87.805,74.807,5.647,73.821,264,knn,8,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
29,65.854,82.609,74.180,4.991,74.191,68.750,85.385,78.149,5.554,78.207,...,74.509,66.667,84.615,75.856,5.400,76.417,224,knn,8,"['diff', 'time', 'opp_elo', 'game_num']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1423,66.667,84.210,73.554,5.956,72.329,71.118,90.265,79.815,7.108,79.219,...,72.715,64.865,84.507,74.072,6.581,73.652,264,knn,39,"['diff', 'game_time', 'elo', 'opp_elo', 'game_..."
1424,63.333,85.714,75.430,7.123,75.658,66.518,91.667,78.944,6.946,79.283,...,76.910,62.069,87.500,76.227,8.053,77.260,187,knn,39,"['diff', 'game_time', 'opp_elo', 'game_num']"
1425,64.706,83.871,73.412,5.543,72.099,72.705,88.889,80.426,6.307,81.788,...,72.485,65.385,85.714,74.157,5.855,73.652,264,knn,39,"['diff', 'game_time', 'opp_elo', 'game_num']"
1426,63.333,92.857,73.037,8.827,71.429,69.866,93.750,80.619,5.909,79.302,...,73.562,64.516,94.118,73.690,8.952,69.694,187,knn,39,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
1427,65.854,86.486,73.237,6.481,72.632,70.333,88.012,78.331,5.665,78.731,...,73.498,65.385,87.180,73.630,6.813,72.002,224,knn,39,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
1428,66.667,79.032,73.414,4.242,73.508,69.099,87.639,79.218,6.122,79.089,...,74.192,66.667,81.159,73.999,5.403,73.765,264,knn,39,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
1429,64.516,87.500,73.718,8.788,70.714,70.000,92.593,79.212,6.687,78.750,...,72.083,59.259,86.956,73.146,10.187,70.833,150,knn,39,"['diff', 'game_time', 'weekday', 'elo', 'opp_e..."
1430,62.857,90.000,74.547,10.329,70.563,67.708,93.056,80.180,7.984,82.229,...,71.389,55.172,88.889,73.285,11.836,72.794,150,knn,39,"['diff', 'game_time', 'weekday', 'elo', 'opp_e..."
1431,66.667,85.714,73.937,7.083,71.464,70.312,89.583,78.380,5.001,77.579,...,74.033,66.667,88.889,74.210,8.206,70.960,187,knn,39,"['diff', 'game_time', 'weekday', 'game_num']"
1432,66.667,82.258,73.566,5.118,73.349,72.127,91.164,80.599,6.348,81.187,...,73.735,64.516,84.507,73.980,6.394,74.788,264,knn,39,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
1433,68.293,81.081,73.516,4.461,73.824,71.894,86.325,77.883,4.560,77.345,...,73.993,66.667,81.081,74.009,4.436,72.949,224,knn,39,"['diff', 'game_time', 'weekday']"
1434,68.628,83.871,74.953,5.356,74.169,68.711,86.622,78.854,6.462,76.518,...,74.924,68.421,86.486,76.715,6.009,75.800,264,knn,39,"['diff', 'game_time']"
1435,63.333,85.714,75.117,7.212,75.063,66.964,91.667,78.951,6.782,79.661,...,76.910,62.069,87.500,75.853,8.127,75.610,187,knn,39,"['diff', 'opp_elo', 'game_num']"
1436,64.706,80.645,73.043,4.889,71.814,71.351,88.750,79.818,6.276,80.000,...,72.485,66.667,82.353,73.708,4.913,73.186,264,knn,39,"['diff', 'opp_elo', 'game_num']"
1437,66.667,80.556,73.194,5.137,73.669,72.779,90.625,80.373,5.678,80.190,...,74.603,66.667,81.250,73.082,5.638,72.069,187,knn,39,"['diff', 'time', 'elo']"
1438,64.706,83.871,73.826,5.841,73.459,69.410,90.370,79.091,6.795,78.935,...,73.852,66.667,86.111,74.622,6.224,73.864,264,knn,39,"['diff', 'time', 'game_time', 'elo', 'opp_elo'..."
1439,62.500,83.333,73.218,7.065,74.743,70.312,90.625,80.230,6.146,79.638,...,76.156,57.143,82.353,72.738,8.012,73.728,187,knn,39,"['diff', 'time', 'game_time', 'elo']"
1440,66.667,81.579,73.356,4.593,72.434,71.118,86.931,79.085,5.740,78.775,...,73.071,67.924,81.159,74.208,4.668,73.186,264,knn,39,"['diff', 'time', 'game_time', 'opp_elo', 'game..."
1441,63.333,85.714,73.537,6.623,72.431,70.660,91.667,80.319,6.868,81.606,...,75.298,62.069,85.714,73.498,7.334,73.107,187,knn,39,"['diff', 'time', 'game_time', 'opp_elo']"
1442,65.790,85.714,73.357,6.742,73.214,67.535,88.542,79.025,6.139,78.646,...,73.958,66.667,87.500,74.190,7.393,73.950,187,knn,39,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
1443,66.667,83.871,73.984,5.203,74.292,70.574,90.053,79.433,6.529,79.252,...,74.516,66.667,86.111,74.729,5.941,75.000,264,knn,39,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
1444,66.667,81.579,73.452,4.211,73.635,72.947,88.201,80.288,5.741,81.350,...,74.821,66.667,81.081,74.247,4.589,75.735,264,knn,39,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
1445,65.116,82.051,73.035,4.889,73.401,71.524,82.487,77.706,3.381,78.473,...,73.458,66.667,82.927,73.776,4.906,72.709,224,knn,39,"['diff', 'time', 'opp_elo', 'game_num']"
1446,68.628,81.579,73.485,4.366,72.835,72.283,87.361,79.577,5.270,79.285,...,73.006,69.231,81.081,74.178,4.090,72.571,264,knn,39,"['diff', 'time', 'opp_elo', 'game_num']"
1447,63.333,78.571,73.447,5.281,74.405,71.354,91.667,80.583,6.721,82.226,...,76.290,62.069,80.000,73.832,5.688,73.876,187,knn,39,"['diff', 'time', 'opp_elo']"
1448,65.790,85.714,73.270,7.027,71.429,68.750,89.583,79.042,6.022,79.440,...,72.396,66.667,87.500,73.995,7.503,72.381,187,knn,39,"['diff', 'time', 'weekday', 'elo', 'opp_elo', ..."
1449,64.706,86.842,73.624,5.879,73.378,69.177,89.048,79.507,6.239,78.693,...,74.261,65.385,86.486,73.728,6.472,72.405,264,knn,39,"['diff', 'weekday', 'elo', 'game_num']"
1450,62.162,90.000,73.686,11.027,69.585,67.500,93.056,80.312,7.281,81.952,...,71.389,53.846,88.889,71.867,13.457,72.794,150,knn,39,"['diff', 'weekday', 'elo', 'opp_elo']"
1451,65.217,85.714,73.425,7.531,71.464,69.866,88.542,78.213,5.223,77.315,...,74.033,66.667,87.500,74.141,7.882,71.068,187,knn,39,"['diff', 'weekday', 'game_num']"
1452,66.667,83.871,74.126,6.355,71.585,68.323,86.878,78.458,6.508,76.334,...,72.156,66.667,86.486,75.047,7.226,73.682,264,knn,39,['diff']

## SVC

In [13]:
svc_list = [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0]
svc_results = results_df_gen()
for hp in svc_list:
    svc_results = gen_best_result_df('svc', hp, svc_results)
svc_results

,min_accu,max_accu,mean_accu,std_accu,mdn_accu,min_auc,max_auc,mean_auc,std_auc,mdn_auc,...,mdn_bal,min_f1,max_f1,mean_f1,std_f1,mdn_f1,df_len,model,hp,cols
0,64.865,88.000,73.207,6.971,71.965,66.667,100.000,78.887,10.243,76.827,...,72.232,64.865,90.909,73.801,8.009,73.097,264,svc,-1.0,"['diff', 'color', 'opp_elo']"
1,55.263,89.474,73.241,8.606,74.405,63.585,98.889,78.356,10.010,78.051,...,74.876,45.161,90.000,72.742,11.421,74.085,187,svc,-1.0,"['diff', 'elo', 'game_num']"
2,67.568,90.000,73.976,6.675,71.965,67.912,91.729,78.128,7.115,75.598,...,71.426,65.517,88.889,73.875,7.711,71.755,264,svc,-1.0,"['diff', 'elo', 'game_num']"
3,60.526,89.474,73.227,7.668,73.573,66.387,98.889,79.517,9.912,76.711,...,74.154,54.546,90.000,73.472,9.345,74.085,187,svc,-1.0,"['diff', 'elo', 'opp_elo', 'game_num']"
4,66.038,87.500,73.226,6.710,71.258,71.169,91.980,77.893,7.244,75.387,...,71.151,65.574,86.486,73.081,7.972,68.496,264,svc,-1.0,"['diff', 'elo', 'opp_elo', 'game_num']"
5,63.158,83.721,73.467,6.097,74.679,70.308,96.667,80.236,8.203,80.087,...,74.216,56.250,82.927,74.318,7.818,76.393,187,svc,-1.0,"['diff', 'game_time', 'opp_elo', 'game_num']"
6,66.000,80.000,73.176,4.311,72.119,71.192,88.889,78.934,6.072,77.875,...,72.836,60.465,84.848,73.531,6.702,73.460,264,svc,-1.0,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
7,60.526,89.474,74.474,7.729,74.679,69.737,95.556,79.340,7.686,78.302,...,74.216,51.613,90.000,74.854,9.782,76.393,187,svc,-1.0,"['diff', 'opp_elo', 'game_num']"
8,60.606,92.308,73.722,11.211,71.714,62.500,100.000,78.022,13.143,73.442,...,74.215,38.095,93.333,69.815,16.356,70.952,150,svc,-1.0,"['diff', 'opp_elo']"
9,64.865,88.000,73.798,7.680,72.842,61.988,98.413,78.162,10.803,76.415,...,73.193,64.865,90.909,73.810,8.909,72.917,264,svc,-1.0,"['diff', 'opp_elo']"
10,60.000,81.818,73.654,7.204,75.275,74.605,89.174,81.805,5.444,81.774,...,75.496,60.000,84.615,74.230,8.548,75.962,187,svc,-1.0,['diff']
11,64.151,85.714,73.147,7.775,71.356,65.790,96.825,79.949,8.950,79.530,...,71.820,64.865,87.671,74.029,8.623,72.651,264,svc,-1.0,['diff']
12,63.636,81.081,73.668,4.509,73.459,70.221,88.304,77.442,5.155,77.338,...,74.426,62.500,81.081,74.698,5.097,75.379,264,svc,-0.5,"['diff', 'color', 'opp_elo', 'game_num']"
13,66.667,80.000,73.340,4.123,72.872,69.818,86.257,79.277,4.756,78.688,...,72.794,65.116,81.690,74.665,5.066,75.000,264,svc,-0.5,"['diff', 'game_num']"
14,68.889,81.818,75.516,4.071,75.205,70.000,84.649,78.763,4.153,78.772,...,75.863,68.182,82.051,76.799,4.576,77.599,264,svc,-0.5,"['diff', 'game_time', 'weekday', 'game_num']"
15,68.966,77.500,73.256,2.626,73.153,68.727,85.965,78.378,5.061,79.326,...,74.113,69.565,79.070,74.609,2.902,75.205,264,svc,-0.5,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
16,67.924,79.365,73.500,4.145,72.457,68.182,87.134,77.823,5.268,78.287,...,72.885,69.565,81.159,74.573,3.954,74.352,264,svc,-0.5,"['diff', 'opp_elo', 'game_num']"
17,65.517,78.378,73.368,4.206,74.578,70.182,86.550,77.367,4.976,76.744,...,75.488,62.857,80.000,73.065,5.404,75.000,264,svc,-0.5,"['diff', 'weekday', 'elo', 'opp_elo', 'game_num']"
18,65.000,86.486,74.408,6.461,74.244,69.091,86.071,78.214,4.856,77.792,...,74.226,68.182,87.180,75.869,6.646,76.487,264,svc,-0.5,"['diff', 'weekday', 'game_num']"
19,65.517,75.758,73.472,3.142,74.802,67.636,85.965,77.854,4.773,78.514,...,74.643,68.750,78.873,74.479,3.112,75.338,264,svc,-0.5,"['diff', 'weekday', 'opp_elo', 'game_num']"
20,66.667,81.081,73.391,5.040,73.055,71.324,88.061,78.010,5.903,78.325,...,74.235,66.667,81.818,73.702,5.189,74.497,264,svc,-0.5,"['diff', 'weekday', 'opp_elo']"
21,63.636,87.302,73.404,6.921,72.019,70.098,88.214,77.658,5.793,76.568,...,72.281,64.865,88.571,73.841,7.699,72.172,264,svc,-0.5,"['diff', 'weekday']"
22,65.000,84.127,73.610,5.773,74.008,69.853,89.133,78.922,6.013,78.338,...,74.257,65.000,86.111,74.661,6.606,74.668,264,svc,-0.5,['diff']
23,65.217,86.364,73.848,6.448,71.652,72.768,81.667,78.747,2.619,79.316,...,73.512,68.293,88.000,73.932,6.525,70.484,187,svc,0.0,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
24,66.667,81.818,73.107,5.087,72.483,73.214,83.333,78.257,3.709,77.585,...,74.482,66.667,83.333,73.625,5.503,74.085,187,svc,0.0,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
25,67.442,81.818,73.772,5.054,72.483,71.825,83.810,77.131,4.071,76.305,...,74.482,68.182,83.333,74.256,5.448,74.085,187,svc,0.0,"['diff', 'weekday', 'opp_elo', 'game_num']"
26,62.903,85.185,73.464,6.180,72.850,69.643,88.958,79.960,7.230,80.969,...,74.423,61.017,85.185,74.241,6.433,74.597,299,svc,0.5,"['diff', 'color', 'time', 'elo', 'opp_elo', 'g..."
27,62.903,82.353,73.075,5.800,72.850,70.263,88.203,79.329,6.868,80.804,...,73.684,61.017,83.333,73.901,6.493,73.329,299,svc,0.5,"['diff', 'color', 'time', 'weekday', 'elo', 'o..."
28,66.129,83.333,73.038,5.600,72.108,69.118,90.398,79.592,6.533,79.256,...,74.454,62.857,83.636,72.992,6.516,73.438,299,svc,0.5,"['diff', 'elo']"
29,64.516,83.333,73.097,5.945,72.301,70.903,90.261,79.594,6.225,79.055,...,73.613,62.857,83.636,73.170,7.076,73.080,299,svc,0.5,"['diff', 'game_time', 'elo']"
30,63.044,81.818,73.199,6.588,72.249,70.588,83.041,79.395,3.786,81.089,...,72.569,65.306,83.333,73.273,6.805,71.364,187,svc,0.5,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
31,66.129,79.630,73.955,4.213,74.245,71.053,88.066,79.570,5.592,79.555,...,75.302,64.407,81.081,74.277,5.706,74.848,299,svc,0.5,"['diff', 'game_time', 'weekday', 'elo', 'opp_e..."
32,66.129,79.412,73.583,3.835,72.850,68.684,87.243,79.215,6.201,79.337,...,74.416,64.407,81.081,74.234,5.043,74.008,299,svc,0.5,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
33,62.903,81.482,73.773,5.368,72.534,70.000,87.860,79.569,6.596,80.994,...,74.921,62.295,82.143,74.535,5.826,74.643,299,svc,0.5,"['diff', 'opp_elo', 'game_num']"
34,62.903,85.185,74.365,5.793,73.443,68.067,88.340,79.474,6.491,79.811,...,74.293,61.017,85.185,74.785,6.474,74.342,299,svc,0.5,"['diff', 'time', 'elo', 'opp_elo', 'game_num']"
35,64.516,81.482,73.046,4.971,72.402,70.168,88.203,79.498,5.823,79.953,...,72.897,62.069,82.143,73.330,6.312,73.221,299,svc,0.5,"['diff', 'time', 'game_time', 'elo', 'opp_elo'..."
36,66.129,79.630,73.065,4.378,72.596,70.526,88.066,79.666,5.925,79.266,...,73.016,64.407,81.081,73.419,5.823,72.899,299,svc,0.5,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
37,61.290,85.185,73.442,6.307,72.596,68.592,88.333,79.967,7.010,81.125,...,75.118,61.290,85.185,74.220,6.610,74.342,299,svc,0.5,"['diff', 'time', 'opp_elo', 'game_num']"
38,67.742,81.482,73.378,4.241,72.596,70.483,87.860,79.501,6.329,79.125,...,73.948,66.667,82.143,74.048,4.976,73.509,299,svc,0.5,"['diff', 'time', 'weekday', 'elo', 'opp_elo', ..."
39,66.129,79.630,73.343,4.130,73.411,69.474,88.477,79.513,7.040,80.359,...,73.555,65.574,81.081,74.208,4.657,73.577,299,svc,0.5,"['diff', 'time', 'weekday', 'opp_elo', 'game_n..."
40,66.129,79.630,73.473,4.158,72.850,67.632,87.917,79.317,6.957,80.380,...,74.423,64.407,81.081,74.076,5.279,74.342,299,svc,0.5,"['diff', 'weekday', 'opp_elo', 'game_num']"
41,66.000,83.607,73.158,5.148,73.030,70.531,89.107,79.500,6.313,81.566,...,74.359,65.306,84.848,73.136,5.655,72.429,264,svc,1.0,"['diff', 'game_time', 'elo', 'game_num']"
42,64.407,88.889,73.120,7.192,71.853,70.312,89.163,77.718,6.582,76.457,...,72.619,64.407,89.286,73.623,7.131,71.198,299,svc,1.0,"['diff', 'time', 'elo', 'opp_elo', 'game_num']"
43,62.000,80.328,73.303,5.263,75.192,70.661,86.492,78.614,6.018,79.934,...,75.469,64.151,82.353,73.692,5.376,73.509,264,svc,1.0,"['diff', 'weekday', 'game_num']"
44,62.000,85.714,73.217,6.680,73.765,65.700,94.805,78.850,9.157,77.181,...,74.907,62.745,87.671,74.161,7.633,73.770,264,svc,1.5,"['diff', 'opp_elo']"

## Ada Boost Classifier

In [16]:
abc_list = [0.25, 0.251, 0.252, 0.253, 0.85, 0.851, 0.852, 0.853,
            1.45, 1.451, 1.452, 1.453, 2.05, 2.051, 2.052, 2.053,
            2.65, 2.651, 2.652, 2.653, 3.25, 3.251, 3.252, 3.253,
            3.85]
#  3.851, 3.852, 3.853, 4.45, 4.451, 4.452, 4.453
abc_results = results_df_gen()
for hp in abc_list:
    abc_results = gen_best_result_df('ada_boost', hp, abc_results)
abc_results

,min_accu,max_accu,mean_accu,std_accu,mdn_accu,min_auc,max_auc,mean_auc,std_auc,mdn_auc,...,mdn_bal,min_f1,max_f1,mean_f1,std_f1,mdn_f1,df_len,model,hp,cols
0,60.000,90.000,74.321,9.925,71.342,69.583,91.667,77.731,6.699,76.272,...,75.206,46.154,88.889,72.229,12.965,72.150,150,ada_boost,0.251,"['color', 'game_time', 'weekday', 'elo', 'opp_..."
1,62.857,85.714,73.746,7.781,74.045,64.583,89.583,77.249,7.979,76.433,...,76.534,55.172,84.210,72.000,9.457,73.030,150,ada_boost,0.251,"['color', 'time', 'elo', 'opp_elo']"
2,62.857,85.714,73.746,7.781,74.045,64.583,89.583,77.249,7.979,76.433,...,76.534,55.172,84.210,72.000,9.457,73.030,150,ada_boost,0.251,"['color', 'time', 'game_time', 'elo', 'opp_elo']"
3,62.857,85.714,73.846,8.064,72.693,64.167,91.667,76.522,7.735,76.274,...,74.843,55.172,84.210,72.405,9.823,72.778,150,ada_boost,0.251,"['color', 'time', 'game_time', 'weekday', 'elo..."
4,62.857,85.714,73.846,8.064,72.693,64.167,91.667,76.522,7.735,76.274,...,74.843,55.172,84.210,72.405,9.823,72.778,150,ada_boost,0.251,"['color', 'time', 'weekday', 'elo', 'opp_elo']"
5,60.000,90.000,74.321,9.925,71.342,69.583,91.667,77.731,6.699,76.272,...,75.206,46.154,88.889,72.229,12.965,72.150,150,ada_boost,0.251,"['color', 'weekday', 'elo', 'opp_elo']"
6,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.641,6.200,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'elo', 'game_num']"
7,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.723,6.286,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'elo']"
8,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.641,6.200,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'game_time', 'elo', 'game_num']"
9,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.723,6.286,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'game_time', 'elo']"
10,61.364,81.967,73.153,5.780,73.130,68.698,90.850,79.913,6.451,80.294,...,73.370,60.465,84.932,73.039,7.457,71.915,264,ada_boost,0.251,"['diff', 'color', 'game_time', 'opp_elo', 'gam..."
11,61.364,81.967,73.153,5.780,73.130,68.698,91.285,79.996,6.571,80.294,...,73.370,60.465,84.932,73.039,7.457,71.915,264,ada_boost,0.251,"['diff', 'color', 'game_time', 'opp_elo']"
12,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.641,6.200,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'game_time', 'weekday', 'elo..."
13,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.684,6.244,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'game_time', 'weekday', 'elo']"
14,61.364,81.967,73.153,5.780,73.130,68.595,91.013,79.819,6.443,79.995,...,73.370,60.465,84.932,73.039,7.457,71.915,264,ada_boost,0.251,"['diff', 'color', 'game_time', 'weekday', 'opp..."
15,61.364,81.967,73.153,5.780,73.130,68.595,91.013,79.853,6.469,79.995,...,73.370,60.465,84.932,73.039,7.457,71.915,264,ada_boost,0.251,"['diff', 'color', 'game_time', 'weekday', 'opp..."
16,61.364,81.967,73.153,5.780,73.130,68.698,90.850,79.913,6.451,80.294,...,73.370,60.465,84.932,73.039,7.457,71.915,264,ada_boost,0.251,"['diff', 'color', 'opp_elo', 'game_num']"
17,61.364,81.967,73.153,5.780,73.130,68.698,91.285,79.996,6.571,80.294,...,73.370,60.465,84.932,73.039,7.457,71.915,264,ada_boost,0.251,"['diff', 'color', 'opp_elo']"
18,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.668,6.286,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'time', 'elo', 'game_num']"
19,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.668,6.286,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'time', 'elo']"
20,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.668,6.286,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'elo', ..."
21,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.668,6.286,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'elo']"
22,61.364,83.607,73.317,6.073,73.130,68.698,89.924,79.756,6.308,80.294,...,73.370,60.465,86.111,73.157,7.673,71.915,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'opp_el..."
23,61.364,83.607,73.317,6.073,73.130,68.698,89.924,79.782,6.327,80.294,...,73.370,60.465,86.111,73.157,7.673,71.915,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'opp_elo']"
24,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.677,6.297,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'weekda..."
25,64.151,82.759,73.475,6.934,73.398,69.800,88.726,79.677,6.297,79.797,...,73.892,63.415,83.077,74.271,6.966,74.523,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'weekda..."
26,65.909,80.328,73.084,5.712,74.305,69.318,85.512,78.692,6.079,78.348,...,74.008,63.415,83.784,74.686,6.731,74.213,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'weekda..."
27,61.364,83.607,73.317,6.073,73.130,68.595,89.924,79.709,6.315,79.995,...,73.370,60.465,86.111,73.157,7.673,71.915,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'weekda..."
28,61.364,83.607,73.317,6.073,73.130,68.595,89.924,79.709,6.315,79.995,...,73.370,60.465,86.111,73.157,7.673,71.915,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'weekda..."
29,65.909,80.328,73.084,5.712,74.305,69.318,85.512,78.711,6.073,78.348,...,74.008,63.415,83.784,74.686,6.731,74.213,264,ada_boost,0.251,"['diff', 'color', 'time', 'game_time', 'weekday']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
990,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time', 'game_time', 'weekday', 'elo']"
991,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time', 'game_time', 'weekday', 'game..."
992,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
993,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
994,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time', 'game_time', 'weekday']"
995,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time', 'game_time']"
996,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'opp_elo', 'game_num']"
997,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'opp_elo']"
998,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time', 'weekday', 'elo', 'game_num']"
999,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'weekday', 'elo', 'opp_elo', ..."
1000,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'weekday', 'elo', 'opp_elo']"
1001,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time', 'weekday', 'elo']"
1002,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time', 'weekday', 'game_num']"
1003,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'weekday', 'opp_elo', 'game_n..."
1004,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'time', 'weekday', 'opp_elo']"
1005,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time', 'weekday']"
1006,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'time']"
1007,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'weekday', 'elo', 'game_num']"
1008,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'weekday', 'elo', 'opp_elo', 'game_num']"
1009,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'weekday', 'elo', 'opp_elo']"
1010,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'weekday', 'elo']"
1011,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'weekday', 'game_num']"
1012,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'weekday', 'opp_elo', 'game_num']"
1013,61.290,89.474,73.863,8.886,72.931,61.042,86.364,77.165,8.368,80.191,...,75.595,51.852,87.500,71.858,10.824,71.848,150,ada_boost,3.253,"['diff', 'weekday', 'opp_elo']"
1014,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,"['diff', 'weekday']"
1015,61.290,86.207,74.705,8.824,75.128,61.042,89.141,78.136,9.077,82.051,...,75.655,51.852,88.235,72.740,11.186,74.599,150,ada_boost,3.253,['diff']
1016,63.889,89.474,75.456,8.237,76.393,64.921,89.204,77.300,7.456,78.030,...,77.489,55.172,87.500,74.830,9.660,75.073,150,ada_boost,3.253,"['game_time', 'elo', 'opp_elo', 'game_num']"
1017,63.889,89.474,75.456,8.237,76.393,64.921,89.204,77.300,7.456,78.030,...,77.489,55.172,87.500,74.830,9.660,75.073,150,ada_boost,3.253,"['game_time', 'weekday', 'elo', 'opp_elo']"
1018,63.889,89.474,75.456,8.237,76.393,64.921,89.204,77.300,7.456,78.030,...,77.489,55.172,87.500,74.830,9.660,75.073,150,ada_boost,3.253,"['time', 'game_time', 'weekday', 'elo', 'opp_e..."

## Random Forest Classifier

In [17]:
rf_results = results_df_gen()
for hp in (range(1, 5)):
    rf_results = gen_best_result_df('random_forest', hp, rf_results)
rf_results

,min_accu,max_accu,mean_accu,std_accu,mdn_accu,min_auc,max_auc,mean_auc,std_auc,mdn_auc,...,mdn_bal,min_f1,max_f1,mean_f1,std_f1,mdn_f1,df_len,model,hp,cols
0,64.444,80.435,73.418,4.715,73.509,65.810,90.598,78.874,7.088,78.044,...,73.672,65.217,80.851,73.449,5.418,74.167,187,random_forest,1,"['diff', 'color', 'game_time', 'elo', 'game_num']"
1,61.290,84.210,73.165,7.998,74.295,63.750,91.282,78.462,9.223,76.730,...,75.224,53.333,84.210,72.562,9.918,75.962,150,random_forest,1,"['diff', 'color', 'game_time', 'elo']"
2,66.667,80.435,73.045,5.194,73.750,68.529,88.095,77.963,7.011,77.162,...,74.373,62.500,80.851,73.129,6.491,74.085,187,random_forest,1,"['diff', 'color', 'game_time', 'weekday', 'elo..."
3,67.647,86.364,73.089,6.508,70.135,70.000,85.354,76.581,6.328,75.060,...,74.116,59.259,85.714,71.355,8.304,68.858,150,random_forest,1,"['diff', 'color', 'time', 'game_time', 'opp_el..."
4,65.714,86.486,73.253,6.124,71.964,66.667,91.813,79.233,7.406,78.200,...,72.000,64.706,85.714,73.592,6.026,73.500,264,random_forest,1,"['diff', 'elo', 'opp_elo', 'game_num']"
5,64.516,83.721,73.060,6.419,72.188,72.647,88.426,78.596,5.254,77.191,...,72.738,62.500,86.274,73.886,7.447,74.235,187,random_forest,1,"['diff', 'game_time', 'game_num']"
6,65.714,83.784,73.557,5.035,73.107,70.194,90.936,78.281,6.391,77.966,...,74.496,64.706,82.353,72.960,5.115,72.391,264,random_forest,1,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
7,69.492,82.759,74.804,4.154,73.333,71.226,87.427,78.695,5.490,79.007,...,74.094,70.000,80.000,74.659,3.655,74.661,264,random_forest,1,"['diff', 'game_time', 'weekday', 'game_num']"
8,67.857,82.500,73.013,4.600,71.548,72.387,91.579,79.354,5.985,77.828,...,71.980,66.667,82.051,72.594,4.948,72.662,264,random_forest,1,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
9,60.000,83.784,73.147,6.646,73.942,71.569,87.427,78.886,5.140,78.575,...,73.500,61.111,81.250,72.680,6.200,73.810,264,random_forest,1,"['diff', 'opp_elo', 'game_num']"
10,64.516,79.412,73.014,4.853,72.023,72.982,85.208,78.545,4.325,77.723,...,73.177,65.625,80.000,73.129,4.872,73.633,299,random_forest,1,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
11,64.516,86.364,73.367,6.725,72.201,66.667,83.529,76.273,5.300,75.449,...,73.456,61.538,85.714,71.821,7.983,70.000,150,random_forest,1,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
12,63.158,84.000,74.696,5.846,74.696,66.250,80.769,75.569,5.059,76.623,...,76.726,64.516,83.333,74.753,6.140,76.945,150,random_forest,1,"['diff', 'weekday', 'game_num']"
13,64.407,82.759,73.290,5.498,71.868,69.548,85.263,77.406,5.380,77.752,...,71.953,65.574,81.081,73.087,5.725,72.049,264,random_forest,1,"['diff', 'weekday', 'game_num']"
14,66.102,77.500,73.583,3.769,75.278,70.387,91.053,79.570,6.048,79.268,...,75.292,68.182,77.612,73.390,3.422,74.180,264,random_forest,1,"['diff', 'weekday', 'opp_elo', 'game_num']"
15,63.158,82.500,73.029,6.197,72.611,70.402,88.972,78.435,5.529,77.849,...,73.265,63.158,82.857,73.711,6.182,73.821,264,random_forest,2,"['diff', 'color', 'elo', 'opp_elo', 'game_num']"
16,63.415,83.721,73.275,6.318,73.381,70.833,89.474,78.380,6.187,78.408,...,73.470,61.538,82.051,73.092,7.080,71.556,224,random_forest,2,"['diff', 'color', 'game_time', 'weekday', 'elo..."
17,66.667,82.609,73.006,5.185,73.072,68.750,84.952,77.527,5.813,77.471,...,72.962,66.667,81.818,73.312,5.550,72.693,187,random_forest,2,"['diff', 'color', 'game_time', 'weekday', 'elo..."
18,63.415,85.714,73.597,7.494,72.657,72.337,87.939,79.007,5.988,78.097,...,74.637,58.333,86.486,73.078,8.628,73.889,224,random_forest,2,"['diff', 'color', 'game_time', 'weekday', 'elo..."
19,68.421,85.000,73.252,4.716,71.763,69.971,88.722,78.295,5.811,78.324,...,72.075,68.421,84.210,73.863,4.868,73.304,264,random_forest,2,"['diff', 'color', 'game_time', 'weekday', 'elo..."
20,63.415,86.046,73.635,8.255,72.369,70.710,87.939,77.964,6.055,77.292,...,73.812,61.224,86.486,73.511,8.901,73.320,224,random_forest,2,"['diff', 'color', 'weekday', 'elo', 'opp_elo',..."
21,65.790,82.500,73.088,6.188,69.852,71.049,93.233,78.758,6.460,77.255,...,70.417,64.865,82.667,74.081,6.130,74.456,264,random_forest,2,"['diff', 'elo', 'opp_elo', 'game_num']"
22,65.385,84.210,75.008,6.350,75.477,67.800,84.091,78.613,5.239,79.610,...,75.815,64.000,82.353,75.617,6.307,77.187,224,random_forest,2,"['diff', 'game_time', 'game_num']"
23,67.273,82.500,73.248,5.243,72.528,74.856,90.226,79.399,4.671,78.518,...,72.640,64.706,81.159,73.243,5.138,72.144,264,random_forest,2,"['diff', 'game_time', 'opp_elo', 'game_num']"
24,63.158,90.000,73.760,7.344,73.198,69.253,90.727,78.280,6.503,77.603,...,73.751,63.158,89.474,74.134,7.433,72.574,264,random_forest,2,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
25,63.636,81.967,73.321,5.667,73.863,65.948,84.423,76.785,6.117,77.092,...,74.673,68.000,84.507,74.641,5.558,74.167,264,random_forest,2,"['diff', 'game_time', 'weekday', 'elo', 'opp_e..."
26,67.273,82.500,73.075,4.447,72.428,69.828,85.714,77.153,4.900,77.556,...,72.889,70.000,82.051,74.074,4.299,71.938,264,random_forest,2,"['diff', 'game_time', 'weekday', 'game_num']"
27,60.976,88.571,74.457,8.469,75.017,70.267,86.404,77.718,5.338,77.109,...,75.860,60.000,88.889,74.673,8.970,75.616,224,random_forest,2,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
28,65.454,80.000,73.321,4.351,73.117,70.259,88.722,78.226,5.661,78.822,...,73.297,69.841,77.778,73.759,3.041,73.254,264,random_forest,2,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
29,56.098,85.714,73.175,7.693,72.850,70.513,86.601,76.653,6.135,74.017,...,74.479,55.000,85.714,73.251,8.294,73.684,224,random_forest,2,"['diff', 'game_time', 'weekday', 'opp_elo']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,67.391,80.000,73.054,4.884,72.136,66.541,87.500,78.971,6.319,78.980,...,71.966,66.667,80.000,72.982,5.416,70.995,187,random_forest,4,"['diff', 'color', 'elo', 'game_num']"
67,65.385,80.000,73.482,4.885,73.974,65.406,87.500,79.509,6.699,78.629,...,75.022,64.000,80.000,73.529,5.125,73.506,187,random_forest,4,"['diff', 'color', 'game_time', 'elo', 'game_num']"
68,61.290,84.615,73.242,7.368,70.900,67.582,92.500,76.478,8.388,73.796,...,72.494,62.500,85.714,73.075,7.722,72.078,150,random_forest,4,"['diff', 'color', 'game_time', 'game_num']"
69,65.217,82.353,73.095,4.578,72.813,72.533,84.429,79.394,3.339,79.970,...,74.038,63.636,82.353,72.814,5.141,73.320,224,random_forest,4,"['diff', 'color', 'game_time', 'opp_elo', 'gam..."
70,66.667,82.353,73.701,4.648,73.774,70.933,83.333,77.694,4.378,78.596,...,75.116,63.415,83.333,72.659,6.616,73.542,224,random_forest,4,"['diff', 'color', 'game_time', 'weekday', 'elo..."
71,63.636,85.294,73.083,6.148,73.025,71.867,82.600,77.982,3.441,79.334,...,74.594,58.333,85.714,72.024,7.468,72.846,224,random_forest,4,"['diff', 'color', 'game_time', 'weekday', 'elo..."
72,67.442,76.471,73.147,3.016,74.331,72.667,82.692,78.038,4.048,79.224,...,74.615,69.231,77.778,73.620,3.243,74.235,224,random_forest,4,"['diff', 'color', 'opp_elo', 'game_num']"
73,61.538,80.000,73.105,6.170,75.140,70.132,83.333,77.098,5.637,76.479,...,74.975,61.538,80.000,73.620,6.597,75.474,187,random_forest,4,"['diff', 'color', 'weekday', 'elo', 'opp_elo',..."
74,64.516,80.000,73.095,5.542,74.680,65.385,95.000,79.009,9.578,78.482,...,77.041,57.143,78.571,72.570,6.567,73.509,150,random_forest,4,"['diff', 'color', 'weekday', 'opp_elo', 'game_..."
75,64.444,82.353,73.181,5.806,74.464,71.467,82.308,78.198,3.928,79.448,...,74.808,61.905,82.353,72.713,6.991,75.236,224,random_forest,4,"['diff', 'color', 'weekday', 'opp_elo', 'game_..."
76,60.870,85.714,74.121,7.512,73.155,67.108,95.833,80.846,8.892,78.161,...,73.155,60.870,87.500,72.801,8.163,71.192,187,random_forest,4,"['diff', 'elo', 'game_num']"
77,65.454,78.261,73.117,3.703,74.443,70.467,84.468,77.845,4.370,79.018,...,74.356,62.745,80.000,74.427,4.829,75.093,224,random_forest,4,"['diff', 'game_num']"
78,65.217,80.000,73.079,4.821,73.214,66.730,95.833,80.227,8.687,77.268,...,73.958,66.667,80.000,72.519,5.089,72.078,187,random_forest,4,"['diff', 'game_time', 'elo', 'game_num']"
79,61.538,85.714,73.066,8.188,73.016,69.583,93.750,78.172,8.138,76.040,...,73.016,58.333,88.889,73.205,9.368,72.503,187,random_forest,4,"['diff', 'game_time', 'game_num']"
80,67.273,79.412,73.689,3.870,74.376,67.200,85.059,78.634,5.035,80.308,...,74.336,64.000,81.081,74.503,5.075,74.755,224,random_forest,4,"['diff', 'game_time', 'game_num']"
81,62.791,88.235,73.720,7.026,74.053,71.600,85.207,78.250,5.211,76.453,...,74.594,65.217,88.235,73.640,7.124,75.595,224,random_forest,4,"['diff', 'game_time', 'opp_elo', 'game_num']"
82,63.044,83.333,73.876,6.303,74.405,67.675,95.833,80.294,8.596,78.462,...,75.116,63.830,82.353,73.894,6.491,74.456,187,random_forest,4,"['diff', 'game_time', 'weekday', 'elo', 'game_..."
83,57.692,100.000,74.415,12.211,72.811,70.000,100.000,79.332,10.673,75.033,...,73.659,56.000,100.000,74.743,12.299,74.166,187,random_forest,4,"['diff', 'game_time', 'weekday', 'game_num']"
84,68.889,80.645,74.247,3.930,73.986,68.800,82.308,77.216,4.227,78.849,...,74.479,69.231,83.333,75.022,4.479,75.132,224,random_forest,4,"['diff', 'game_time', 'weekday', 'game_num']"
85,67.500,80.000,73.373,4.338,73.808,68.727,86.124,77.370,5.404,78.623,...,74.856,65.116,78.049,73.156,4.375,74.132,264,random_forest,4,"['diff', 'game_time', 'weekday', 'game_num']"
86,64.444,88.235,73.919,7.291,75.445,70.933,83.077,77.526,4.553,77.079,...,76.319,60.000,88.235,73.268,8.695,74.585,224,random_forest,4,"['diff', 'game_time', 'weekday', 'opp_elo', 'g..."
87,63.044,81.395,73.631,6.364,73.381,70.038,95.833,79.981,7.505,77.941,...,73.274,65.306,85.185,74.123,6.642,71.417,187,random_forest,4,"['diff', 'game_time']"
88,65.957,85.366,73.667,5.982,73.942,73.273,91.388,79.069,5.750,77.520,...,73.779,63.158,85.000,72.595,6.423,73.074,264,random_forest,4,"['diff', 'opp_elo', 'game_num']"
89,63.044,85.714,73.660,6.993,74.051,67.864,97.917,78.873,10.157,74.677,...,75.486,63.830,85.714,73.664,7.254,75.140,187,random_forest,4,"['diff', 'time', 'game_time', 'weekday', 'elo'..."
90,68.852,82.927,73.418,4.866,71.192,70.546,90.909,78.649,6.042,77.182,...,71.409,66.667,81.081,72.329,5.093,71.986,264,random_forest,4,"['diff', 'time', 'game_time', 'weekday', 'opp_..."
91,60.870,92.857,73.918,8.923,74.342,69.943,100.000,79.704,9.433,75.368,...,74.306,60.870,93.333,73.657,9.051,72.953,187,random_forest,4,"['diff', 'time', 'weekday', 'elo', 'game_num']"
92,65.000,82.927,73.093,6.076,73.808,68.182,86.124,76.425,5.864,76.445,...,74.856,65.000,82.051,72.588,5.371,73.765,264,random_forest,4,"['diff', 'weekday', 'game_num']"
93,65.217,88.235,73.673,6.726,73.371,70.800,85.385,77.660,4.923,76.023,...,73.060,63.636,88.235,72.959,7.580,72.585,224,random_forest,4,"['diff', 'weekday', 'opp_elo', 'game_num']"
94,67.500,82.927,73.040,4.951,72.364,71.125,90.191,78.137,5.954,77.170,...,73.114,64.865,81.081,72.461,5.064,72.852,264,random_forest,4,"['diff', 'weekday', 'opp_elo', 'game_num']"
95,64.286,81.395,73.545,5.467,73.381,71.834,93.750,79.676,6.831,77.843,...,73.274,68.085,85.185,74.123,6.027,72.000,187,random_forest,4,['diff']

In [18]:
results_nd = pd.concat([LDA_results, log_results, qda_results, ridge_results,
                        gauz_results, knn_results, svc_results, abc_results,
                        rf_results], axis=0)

In [19]:
results_nd.to_csv('../data/botbrnlys-nd.csv', index=False)